import { ArrowUpRight, Mail, MapPin, Phone } from "lucide-react";
import Link from "next/link";
import { company, locations } from "../company-data";
import { Container } from "../components/container";
import { PageShell } from "../components/page-shell";
import { createPageMetadata } from "../seo";
export const metadata = createPageMetadata({ title: "Contact Kapileshwor Cargo | KCPL Nepal", description: "Contact the KCPL head office in Sorakhutte, Kathmandu for freight enquiries, route coordination and shipment support.", path: "/contact" });
export default function ContactPage(){const directions=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(company.addressLines.join(", "))}`;return <PageShell eyebrow="Contact" title="Talk to KCPL about your cargo." intro="Contact the Kathmandu head office for freight enquiries, route coordination and shipment support.">
  <section className="section bg-white"><Container><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow text-gold">Head office</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.045em] text-navy">Kathmandu, Nepal</h2><div className="mt-10 space-y-7 text-base leading-7 text-slate"><div className="flex gap-4"><MapPin className="mt-1 shrink-0 text-gold" size={20}/><div><address className="not-italic">{company.addressLines.map((line)=><span className="block" key={line}>{line}</span>)}</address><a className="contact-directions" href={directions} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={14}/></a></div></div><p className="flex gap-4"><Phone className="mt-1 shrink-0 text-gold" size={20}/><span><a className="block hover:text-navy" href="tel:+97714987510">{company.phones[0]}</a></span></p><p className="flex gap-4"><Mail className="mt-1 shrink-0 text-gold" size={20}/><a className="break-all hover:text-navy" href={`mailto:${company.email}`}>{company.email}</a></p></div><div className="contact-actions"><Link href="/quote" data-analytics-event="contact_quote_click">Prepare a freight enquiry <ArrowUpRight size={16}/></Link><p>Our team will review enquiries received by email and get in touch.</p></div></div><div className="bg-offwhite p-8 sm:p-12"><p className="eyebrow text-gold">Operational locations</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-.04em] text-navy">Branch network</h2><p className="mt-5 text-sm leading-7 text-slate">Contact the head office for the appropriate branch connection.</p><div className="mt-8 grid grid-cols-2 gap-x-8 gap-y-5 border-t border-line pt-7">{locations.slice(1).map((location)=><span key={location} className="text-sm font-bold text-navy">{location}</span>)}</div></div></div></Container></section>
</PageShell>}
