import {
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  Calendar,
  CheckSquare,
  ClipboardList,
  CreditCard,
  Database,
  FileText,
  Folder,
  Globe,
  Home,
  Layers,
  Map,
  MessageSquare,
  Network,
  Receipt,
  Scale,
  Shield,
  Tag,
  TrendingUp,
  Truck,
  Users,
  Users2,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { WorkspaceIconName } from "./workflow-navigation";

const workspaceIcons: Record<WorkspaceIconName, LucideIcon> = {
  Home,
  Truck,
  Calendar,
  FileText,
  Map,
  Shield,
  Folder,
  CheckSquare,
  Bell,
  BellRing,
  MessageSquare,
  Users,
  TrendingUp,
  BarChart3,
  Tag,
  Layers,
  ClipboardList,
  Globe,
  Zap,
  Network,
  CreditCard,
  Receipt,
  Scale,
  BarChart2,
  Database,
  Users2,
};

export function WorkspaceIcon({ name, size = 17 }: { name: WorkspaceIconName; size?: number }) {
  const Icon = workspaceIcons[name];
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true"/>;
}
