import {
  ArrowLeftRight,
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  BookOpen,
  Calendar,
  CheckSquare,
  ClipboardList,
  CreditCard,
  Database,
  FileText,
  Folder,
  Globe,
  Home,
  Landmark,
  Layers,
  Map,
  MessageSquare,
  Monitor,
  Network,
  Percent,
  Receipt,
  Scale,
  Shield,
  Tag,
  TrendingUp,
  Truck,
  Undo2,
  Users,
  Users2,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { WorkspaceIconName } from "./workflow-navigation";

const workspaceIcons: Record<WorkspaceIconName, LucideIcon> = {
  Undo2,
  Home,
  Truck,
  Calendar,
  FileText,
  Map,
  Shield,
  Folder,
  CheckSquare,
  Bell,
  BellRing,
  MessageSquare,
  Monitor,
  Users,
  TrendingUp,
  BarChart3,
  Tag,
  Layers,
  ClipboardList,
  Globe,
  Zap,
  Network,
  CreditCard,
  Receipt,
  Scale,
  BarChart2,
  Database,
  Users2,
  Landmark,
  BookOpen,
  Wallet,
  ArrowLeftRight,
  Percent,
};

export function WorkspaceIcon({ name, size = 16 }: { name: WorkspaceIconName; size?: number }) {
  const Icon = workspaceIcons[name];
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true"/>;
}
