import type { SiteLocale } from "../site-i18n";

const en = {
  essentials: "Essential details",
  progress: (count: number) => `${count} of 5 entered`,
  route: "Route",
  required: "Required",
  origin: "Origin",
  destination: "Destination",
  cityCountry: "City, country",
  mode: "Freight mode",
  selectMode: "Select mode",
  air: "Air freight",
  sea: "Sea freight",
  road: "Road freight",
  unsure: "Not sure yet",
  cargo: "Cargo profile",
  available: "As available",
  skipCargo: "Skip optional cargo",
  cargoType: "Cargo type",
  cargoExample: "e.g. machinery, cartons, personal effects",
  weight: "Weight",
  dimensions: "Dimensions",
  length: "Length",
  width: "Width",
  height: "Height",
  timing: "Preferred timing",
  timingExample: "Date or timeframe",
  notes: "Special handling or notes",
  notesExample: "Handling requirements, packaging notes, or other relevant details",
  contact: "Your details",
  contactRequired: "Name and email required",
  name: "Name",
  nameExample: "Your name",
  email: "Email",
  emailExample: "you@company.com",
  company: "Company",
  companyExample: "Company name",
  phone: "Phone",
  phoneExample: "Contact number",
  review: "Review and send",
  sendTo: "Send to KCPL.",
  received: "Enquiry received.",
  reviewCopy: "Your route, cargo and contact details will be securely submitted to KCPL for review.",
  receivedCopy: "KCPL has received your freight enquiry. Keep the reference below for follow-up.",
  notProvided: "Not provided",
  reference: "KCPL reference",
  submit: "Submit quote request",
  submitting: "Submitting…",
  success: (reference: string) => `Quote request ${reference} has been stored for KCPL review.`,
  error: "The enquiry could not be submitted. Please try again.",
  unavailable: "Quote submission is unavailable. Please email KCPL instead.",
  invalid: "Please check the required details.",
  rateLimited: "Too many enquiries right now. Please try again shortly.",
  verification: "We could not verify this submission. Please try again.",
  emailFallback: "You can still send the same details by email.",
  emailAction: "Send by email",
  privacy: "KCPL will use the information you submit only to review and respond to this freight enquiry.",
};

export const quoteCopy: Record<SiteLocale, typeof en> = {
  en,
  ne: {
    essentials: "अनिवार्य विवरण",
    progress: (count) => `५ मध्ये ${count} भरियो`,
    route: "रुट",
    required: "अनिवार्य",
    origin: "प्रस्थान स्थान",
    destination: "गन्तव्य",
    cityCountry: "सहर, देश",
    mode: "ढुवानी माध्यम",
    selectMode: "माध्यम छान्नुहोस्",
    air: "हवाई ढुवानी",
    sea: "समुद्री ढुवानी",
    road: "सडक ढुवानी",
    unsure: "अहिले निश्चित छैन",
    cargo: "कार्गो विवरण",
    available: "थाहा भएसम्म",
    skipCargo: "वैकल्पिक कार्गो विवरण छाड्नुहोस्",
    cargoType: "कार्गोको प्रकार",
    cargoExample: "जस्तै मेसिनरी, कार्टन, व्यक्तिगत सामान",
    weight: "तौल",
    dimensions: "नाप",
    length: "लम्बाइ",
    width: "चौडाइ",
    height: "उचाइ",
    timing: "अपेक्षित समय",
    timingExample: "मिति वा समयावधि",
    notes: "विशेष ह्यान्डलिङ वा टिप्पणी",
    notesExample: "ह्यान्डलिङ, प्याकेजिङ वा अन्य सम्बन्धित विवरण",
    contact: "तपाईंको विवरण",
    contactRequired: "नाम र इमेल अनिवार्य",
    name: "नाम",
    nameExample: "तपाईंको नाम",
    email: "इमेल",
    emailExample: "you@company.com",
    company: "कम्पनी",
    companyExample: "कम्पनीको नाम",
    phone: "फोन",
    phoneExample: "सम्पर्क नम्बर",
    review: "जाँचेर पठाउनुहोस्",
    sendTo: "KCPL लाई पठाउनुहोस्।",
    received: "इन्क्वायरी प्राप्त भयो।",
    reviewCopy: "तपाईंको रुट, कार्गो र सम्पर्क विवरण समीक्षाका लागि KCPL मा सुरक्षित रूपमा पठाइनेछ।",
    receivedCopy: "KCPL ले तपाईंको फ्रेट इन्क्वायरी प्राप्त गरेको छ। पछिको सम्पर्कका लागि तलको सन्दर्भ नम्बर राख्नुहोस्।",
    notProvided: "उपलब्ध छैन",
    reference: "KCPL सन्दर्भ",
    submit: "कोटेसन अनुरोध पठाउनुहोस्",
    submitting: "पठाइँदैछ…",
    success: (reference) => `कोटेसन अनुरोध ${reference} KCPL को समीक्षाका लागि सुरक्षित गरिएको छ।`,
    error: "इन्क्वायरी पठाउन सकिएन। कृपया फेरि प्रयास गर्नुहोस्।",
    unavailable: "अहिले कोटेसन अनुरोध पठाउन सकिँदैन। KCPL लाई इमेल गर्नुहोस्।",
    invalid: "कृपया अनिवार्य विवरण जाँच्नुहोस्।",
    rateLimited: "अहिले धेरै अनुरोध आएका छन्। केही बेरपछि फेरि प्रयास गर्नुहोस्।",
    verification: "यो अनुरोध पुष्टि गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।",
    emailFallback: "यही विवरण इमेलबाट पनि पठाउन सक्नुहुन्छ।",
    emailAction: "इमेल पठाउनुहोस्",
    privacy: "KCPL ले तपाईंको विवरण यो फ्रेट इन्क्वायरीको समीक्षा र जवाफ दिन मात्र प्रयोग गर्नेछ।",
  },
  zh: {
    essentials: "必填信息",
    progress: (count) => `已填写 ${count}/5 项`,
    route: "运输路线",
    required: "必填",
    origin: "起运地",
    destination: "目的地",
    cityCountry: "城市、国家",
    mode: "运输方式",
    selectMode: "选择运输方式",
    air: "空运",
    sea: "海运",
    road: "陆运",
    unsure: "暂不确定",
    cargo: "货物信息",
    available: "按已知信息填写",
    skipCargo: "跳过可选货物信息",
    cargoType: "货物类型",
    cargoExample: "例如机械、纸箱或个人物品",
    weight: "重量",
    dimensions: "尺寸",
    length: "长",
    width: "宽",
    height: "高",
    timing: "期望时间",
    timingExample: "日期或时间范围",
    notes: "特殊操作或备注",
    notesExample: "装卸、包装或其他相关要求",
    contact: "联系信息",
    contactRequired: "姓名和邮箱必填",
    name: "姓名",
    nameExample: "您的姓名",
    email: "邮箱",
    emailExample: "you@company.com",
    company: "公司",
    companyExample: "公司名称",
    phone: "电话",
    phoneExample: "联系电话",
    review: "确认并发送",
    sendTo: "发送给 KCPL。",
    received: "询价已收到。",
    reviewCopy: "您的路线、货物和联系信息将安全提交给 KCPL 审核。",
    receivedCopy: "KCPL 已收到您的货运询价。请保存以下编号，以便后续联系。",
    notProvided: "未提供",
    reference: "KCPL 编号",
    submit: "提交报价请求",
    submitting: "正在提交…",
    success: (reference) => `报价请求 ${reference} 已保存，等待 KCPL 审核。`,
    error: "询价未能提交，请重试。",
    unavailable: "暂时无法提交询价，请给 KCPL 发送邮件。",
    invalid: "请检查必填信息。",
    rateLimited: "当前请求过多，请稍后再试。",
    verification: "无法验证本次提交，请重试。",
    emailFallback: "您也可以通过邮件发送相同信息。",
    emailAction: "发送邮件",
    privacy: "KCPL 仅将您提交的信息用于审核并回复本次货运询价。",
  },
  hi: {
    essentials: "ज़रूरी जानकारी",
    progress: (count) => `5 में से ${count} भरे गए`,
    route: "मार्ग",
    required: "ज़रूरी",
    origin: "प्रस्थान स्थान",
    destination: "गंतव्य",
    cityCountry: "शहर, देश",
    mode: "ढुलाई का तरीका",
    selectMode: "तरीका चुनें",
    air: "हवाई माल ढुलाई",
    sea: "समुद्री माल ढुलाई",
    road: "सड़क माल ढुलाई",
    unsure: "अभी तय नहीं",
    cargo: "माल की जानकारी",
    available: "जितनी जानकारी हो",
    skipCargo: "वैकल्पिक माल की जानकारी छोड़ें",
    cargoType: "माल का प्रकार",
    cargoExample: "जैसे मशीनरी, कार्टन, निजी सामान",
    weight: "वज़न",
    dimensions: "माप",
    length: "लंबाई",
    width: "चौड़ाई",
    height: "ऊँचाई",
    timing: "वांछित समय",
    timingExample: "तारीख़ या समय-सीमा",
    notes: "विशेष हैंडलिंग या टिप्पणी",
    notesExample: "हैंडलिंग, पैकिंग या अन्य संबंधित विवरण",
    contact: "आपकी जानकारी",
    contactRequired: "नाम और ईमेल ज़रूरी",
    name: "नाम",
    nameExample: "आपका नाम",
    email: "ईमेल",
    emailExample: "you@company.com",
    company: "कंपनी",
    companyExample: "कंपनी का नाम",
    phone: "फ़ोन",
    phoneExample: "संपर्क नंबर",
    review: "जाँचकर भेजें",
    sendTo: "KCPL को भेजें।",
    received: "पूछताछ प्राप्त हुई।",
    reviewCopy: "आपके मार्ग, माल और संपर्क विवरण समीक्षा के लिए सुरक्षित रूप से KCPL को भेजे जाएंगे।",
    receivedCopy: "KCPL को आपकी फ्रेट पूछताछ मिल गई है। आगे संपर्क के लिए नीचे दिया संदर्भ नंबर सुरक्षित रखें।",
    notProvided: "नहीं दिया गया",
    reference: "KCPL संदर्भ",
    submit: "कोटेशन अनुरोध भेजें",
    submitting: "भेजा जा रहा है…",
    success: (reference) => `कोटेशन अनुरोध ${reference} KCPL की समीक्षा के लिए सुरक्षित कर लिया गया है।`,
    error: "पूछताछ भेजी नहीं जा सकी। कृपया फिर प्रयास करें।",
    unavailable: "अभी कोटेशन अनुरोध नहीं भेजा जा सकता। कृपया KCPL को ईमेल करें।",
    invalid: "कृपया ज़रूरी जानकारी जाँचें।",
    rateLimited: "अभी बहुत अधिक अनुरोध आ रहे हैं। थोड़ी देर बाद फिर प्रयास करें।",
    verification: "यह अनुरोध सत्यापित नहीं हो सका। कृपया फिर प्रयास करें।",
    emailFallback: "आप यही जानकारी ईमेल से भी भेज सकते हैं।",
    emailAction: "ईमेल भेजें",
    privacy: "KCPL आपकी जानकारी का उपयोग केवल इस फ्रेट पूछताछ की समीक्षा और उत्तर देने के लिए करेगा।",
  },
};
