import { ArrowRight } from "lucide-react";
import { Container } from "../components/container";
import { PageShell } from "../components/page-shell";

export default async function QuotePage({ searchParams }: { searchParams: Promise<{ origin?: string; destination?: string; mode?: string }> }) {
  const query = await searchParams;
  const modeLabels: Record<string, string> = { air: "Air freight", sea: "Sea freight", road: "Road freight", unsure: "Not sure yet" };
  return <PageShell eyebrow="Request a quote" title="Tell us where your cargo needs to go." intro="Share the essentials below. The form is presented as a design-ready shell and will be connected during the backend phase."><section className="section bg-offwhite"><Container><form className="mx-auto grid max-w-5xl gap-6 bg-white p-7 shadow-[0_20px_60px_rgba(8,35,63,.08)] sm:grid-cols-2 sm:p-12" aria-label="Quote request form"><Field label="Full name" placeholder="Your name"/><Field label="Company" placeholder="Company name"/><Field label="Email" placeholder="name@company.com" type="email"/><Field label="Phone" placeholder="Phone number"/><Field label="Origin" placeholder="City, country" value={query.origin}/><Field label="Destination" placeholder="City, country" value={query.destination}/><Field label="Freight mode" placeholder="Freight mode" value={query.mode ? modeLabels[query.mode] ?? query.mode : undefined}/><label className="sm:col-span-2"><span className="field-label">Shipment details</span><textarea disabled rows={5} placeholder="Cargo type, weight, dimensions and preferred timeline" className="field-input resize-none"/></label><button disabled className="inline-flex min-h-14 items-center justify-center gap-3 bg-navy px-7 text-xs font-bold uppercase tracking-[.15em] text-white opacity-70 sm:col-span-2 sm:justify-self-start">Submit enquiry <ArrowRight size={16}/></button><p className="text-xs text-slate sm:col-span-2">Form submission is intentionally disabled until backend and confirmed contact routing are provided.</p></form></Container></section></PageShell>;
}

function Field({label,placeholder,type="text",value}:{label:string;placeholder:string;type?:string;value?:string}){return <label><span className="field-label">{label}</span><input disabled type={type} placeholder={placeholder} defaultValue={value} className="field-input"/></label>}
