import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { affiliations, company } from "../company-data";
import { Container } from "../components/container";
import { PageShell } from "../components/page-shell";
export default function AboutPage(){return <PageShell eyebrow="About KCPL" title="Built in Kathmandu. Focused on the route ahead." intro="Kapileshwor Cargo Pvt. Ltd. has coordinated freight and logistics from Nepal since 2015.">
  <section className="section bg-white"><Container><div className="grid gap-14 lg:grid-cols-[.78fr_1.22fr] lg:gap-24"><div><p className="eyebrow text-gold">Our company</p><h2 className="section-title mt-4">Nepal expertise. Cross-border connection.</h2></div><div className="space-y-6 text-base leading-8 text-slate"><p>KCPL was established in Kathmandu in {company.founded} with a focus on practical freight forwarding. The company coordinates air, ocean and road freight for cargo moving within Nepal, across the India border and onward to international markets.</p><p>Its network has grown through operational locations in Nepal and India, personnel positioned across Nepal&apos;s customs entry points, and relationships with international logistics counterparts. These are distinct parts of one coordinated service model.</p><p>Alongside standard freight forwarding, KCPL handles project cargo, break bulk cargo and open top container movements, supported by warehousing, packaging, storage, ground transport and door-to-door delivery.</p></div></div></Container></section>
  <section className="section bg-offwhite"><Container><div className="grid gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div className="leadership-mark aspect-[4/5] border border-line"><span>RM</span><small>KCPL / KATHMANDU</small></div><div><p className="eyebrow text-gold">Leadership</p><h2 className="mt-5 text-4xl font-extrabold tracking-[-.05em] text-navy sm:text-6xl">{company.managingDirector}</h2><p className="mt-3 text-xs font-extrabold uppercase tracking-[.18em] text-gold">Managing Director</p><div className="leadership-experience"><strong>25+</strong><p>More than 25 years of experience in freight forwarding and logistics.</p></div><blockquote className="mt-9 border-l border-gold pl-6 text-xl font-semibold leading-9 tracking-[-.02em] text-navy">“Our work is built on reliability, practical coordination and long-term client relationships. As Nepal&apos;s international connectivity expands, KCPL remains focused on clear service and the quality of every handover.”</blockquote></div></div></Container></section>
  <section className="section bg-navy text-white"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="eyebrow text-gold">Industry network</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.045em]">Professional affiliations.</h2></div><div className="affiliation-list affiliation-list-dark">{affiliations.map((item)=><div key={item.name}><strong>{item.name}</strong><span>{item.detail}</span></div>)}</div></div><Link href="/contact" className="mt-12 inline-flex items-center gap-3 text-xs font-bold uppercase tracking-[.15em] text-gold">Contact KCPL <ArrowRight size={16}/></Link></Container></section>
</PageShell>}
