/*
 * Generates lib/l10n/app_{en,ne}.arb from the web portal's dictionary.
 *
 * The portal's Nepali was written with care for how Kathmandu freight desks
 * actually talk (see app/portal/portal-i18n.ts). The app reuses it rather than
 * keeping a second translation that drifts. Strings only the app needs are
 * kept below, with both languages side by side.
 *
 * Run from the repo root after changing either:
 *   node --experimental-strip-types mobile/tool/sync_portal_strings.mjs
 */
import { writeFileSync } from "node:fs";
import { portalText } from "../../app/portal/portal-i18n.ts";

const portalKeys = `
chrome.overview chrome.shipments chrome.documents chrome.invoices chrome.settings chrome.account
chrome.account_switch_failed chrome.public_site
common.shipment common.route common.status common.documents common.updated common.download common.loading
common.unavailable_title common.unavailable_detail
status.booking_confirmed status.preparing status.in_transit status.customs_clearance
status.out_for_delivery status.delivered status.exception status.unknown
mode.air mode.sea mode.road mode.unsure
invoice.issued invoice.partially_paid invoice.paid invoice.overdue invoice.open
free_time.label free_time.deadline free_time.consequence
fts.not_set fts.expired_yesterday fts.expired_yesterday_at fts.expired_days fts.expired_days_at
fts.last_day fts.last_day_at fts.one_day fts.one_day_at fts.days fts.days_at
role.owner role.member
doc.air_waybill doc.bill_of_lading doc.road_consignment_note doc.shipping_instruction doc.cargo_manifest
doc.pickup_order doc.commercial_invoice doc.packing_list doc.customs_document doc.certificate_of_origin
doc.import_permit doc.export_permit doc.dangerous_goods_declaration doc.insurance_certificate
doc.delivery_order doc.proof_of_delivery doc.other doc.unknown
overview.description overview.kpi_active overview.kpi_in_transit overview.kpi_arriving
overview.kpi_free_time overview.kpi_documents overview.kpi_attention
overview.free_time_title overview.free_time_description
overview.outstanding_title overview.outstanding_description
overview.account_title overview.open_invoices_one overview.open_invoices overview.overdue_count
overview.currency_outstanding overview.amount_overdue overview.nothing_overdue
overview.movements_title overview.all_shipments overview.now_at
overview.empty_delivered_title overview.empty_delivered_description
overview.empty_none_title overview.empty_none_description
overview.paperwork_title overview.all_documents overview.no_documents_title overview.no_documents_description
overview.view_invoices overview.origin overview.destination overview.col_eta
ships.focus_all ships.focus_active ships.focus_in_transit ships.focus_attention ships.focus_delivered
ships.search_placeholder ships.empty_filtered_title ships.empty_filtered_description
ships.empty_title ships.empty_description
docs.coverage docs.all docs.from_kcpl docs.sent_by_you docs.state_confirmed docs.state_resend docs.state_with_kcpl
docs.empty_filtered_title docs.empty_title docs.empty_description docs.search_placeholder
inv.position_title inv.position_description inv.invoiced_receipted inv.billing_title
inv.col_issued inv.col_due inv.col_total inv.col_paid inv.col_balance inv.opening_balance
inv.empty_title inv.empty_description inv.footnote
invd.statement invd.col_charge invd.col_quantity invd.col_unit_price invd.no_lines_title invd.no_lines_description
invd.subtotal invd.tax invd.receipted invd.balance_due invd.issued_on invd.due_on
invd.not_found_title invd.not_found_description invd.no_access_title invd.no_access_description
ship.not_found_title ship.not_found_description ship.opened ship.last_update
ship.free_time_expired_description ship.free_time_description ship.location ship.as_advised
ship.days_overdue ship.days_remaining ship.charge_after_expiry ship.per_day ship.allowance ship.allowance_days
ship.free_time_footnote ship.movement_title ship.mode ship.current_location ship.not_reported ship.eta
ship.carrier_reference ship.to_be_confirmed ship.milestones_title ship.no_milestones_title
ship.no_milestones_description ship.documents_description ship.no_documents_title ship.no_documents_description
ships.col_carrier
topic.shipment_updates topic.documents topic.free_time topic.invoices
topic.shipment_updates_hint topic.documents_hint topic.free_time_hint topic.invoices_hint
settings.email_title settings.email_description settings.save_failed
req.quotes_title req.quotes_description req.col_quote req.col_valid req.ask_to_proceed req.no_quotes_title req.no_quotes_description
req.progress_title req.progress_description req.booking_sent req.booking_failed req.raised_on
req.nothing_waiting_title req.nothing_waiting_description
xchg.title xchg.state_needed xchg.state_resend xchg.state_with_kcpl xchg.state_confirmed
settings.language settings.signed_in_as settings.account settings.access_level settings.provisioning_note
`.trim().split(/\s+/);

/** App-only strings: [key, English, Nepali, placeholder types if not String]. */
const appStrings = [
  ["appTitle", "KCPL", "KCPL"],
  ["signInTitle", "Sign in to KCPL", "KCPL मा साइन इन गर्नुहोस्"],
  ["signInSubtitle", "Your shipments, documents and invoices with Kapileshwor Cargo.", "कपिलेश्वर कार्गोसँगका तपाईंका ढुवानी, कागजात र बिल।"],
  ["emailLabel", "Email address", "इमेल ठेगाना"],
  ["passwordLabel", "Password", "पासवर्ड"],
  ["showPassword", "Show password", "पासवर्ड देखाउनुहोस्"],
  ["hidePassword", "Hide password", "पासवर्ड लुकाउनुहोस्"],
  ["signIn", "Sign in", "साइन इन"],
  ["signingIn", "Signing in…", "साइन इन हुँदैछ…"],
  ["forgotPassword", "Forgot password?", "पासवर्ड बिर्सनुभयो?"],
  ["resetNeedsEmail", "Enter your email address first, then choose Forgot password.", "पहिले इमेल ठेगाना लेख्नुहोस्, त्यसपछि पासवर्ड बिर्सनुभयो? छान्नुहोस्।"],
  ["resetSent", "If that address has KCPL portal access, a password reset link is on its way.", "त्यो ठेगानामा KCPL पोर्टल पहुँच छ भने पासवर्ड रिसेट लिङ्क पठाइँदैछ।"],
  ["signInFailed", "Sign-in failed. Check your details and try again.", "साइन इन हुन सकेन। विवरण जाँचेर फेरि प्रयास गर्नुहोस्।"],
  ["tooManyAttempts", "Too many attempts. Wait a few minutes and try again.", "धेरै पटक प्रयास भयो। केही मिनेट पर्खेर फेरि प्रयास गर्नुहोस्।"],
  ["networkError", "KCPL could not be reached. Check your connection and try again.", "KCPL सम्म पुग्न सकिएन। इन्टरनेट जडान जाँचेर फेरि प्रयास गर्नुहोस्।"],
  ["sessionEnded", "Your session has ended. Sign in again.", "तपाईंको सत्र सकियो। फेरि साइन इन गर्नुहोस्।"],
  ["signOut", "Sign out", "साइन आउट"],
  ["retry", "Try again", "फेरि प्रयास गर्नुहोस्"],
  ["switchAccount", "Switch account", "खाता बदल्नुहोस्"],
  ["downloading", "Downloading…", "डाउनलोड हुँदैछ…"],
  ["downloadFailed", "The document could not be downloaded.", "कागजात डाउनलोड हुन सकेन।"],
  ["documentSaved", "Saved {filename}", "{filename} सुरक्षित भयो"],
  ["helpContact", "Need help? Contact your KCPL account manager.", "सहयोग चाहियो? आफ्नो KCPL खाता प्रबन्धकलाई सम्पर्क गर्नुहोस्।"],
  ["demoBanner", "Demo data, not a real account", "नमुना विवरण, वास्तविक खाता होइन"],
  ["appVersion", "Version {version}", "संस्करण {version}"],
  ["modeRail", "Rail freight", "रेल ढुवानी"],
  ["modeCourier", "Courier", "कुरियर"],
  ["modeMultimodal", "Multimodal", "बहुमाध्यम ढुवानी"],
  ["pushPrimerTitle", "Know the moment your cargo moves", "सामान सर्ने बित्तिकै थाहा पाउनुहोस्"],
  ["pushPrimerBody", "Get a notification when a shipment moves, a document is ready or free time is running out.", "ढुवानी अघि बढ्दा, कागजात तयार हुँदा वा फ्री टाइम सकिन लाग्दा सूचना पाउनुहोस्।"],
  ["pushTurnOn", "Turn on", "खोल्नुहोस्"],
  ["pushNotNow", "Not now", "अहिले होइन"],
  ["pushSection", "Notifications", "सूचना"],
  ["pushSetting", "Push notifications", "पुस सूचना"],
  ["pushOn", "On", "खुला"],
  ["pushOff", "Off", "बन्द"],
  ["pushBlocked", "Blocked in your phone's Settings", "फोनको सेटिङमा रोकिएको"],
  ["pushUnavailable", "Not available in this build", "यो संस्करणमा उपलब्ध छैन"],
  ["pushBlockedHelp", "Allow notifications for KCPL in your phone's Settings.", "फोनको सेटिङमा KCPL का लागि सूचना अनुमति दिनुहोस्।"],
  ["homeOnTheWay", "{count, plural, =0{Nothing on the way} =1{1 shipment on the way} other{{count} shipments on the way}}", "{count, plural, =0{बाटोमा केही छैन} other{{count} ढुवानी बाटोमा}}", { count: "int" }],
  ["homeNeedsAttention", "{count, plural, =1{1 needs attention} other{{count} need attention}}", "{count} मा ध्यान चाहिन्छ", { count: "int" }],
  ["homeArriving", "{count} arriving this week", "{count} यो हप्ता आइपुग्दै", { count: "int" }],
  ["homeAllClear", "Everything is moving as planned", "सबै योजनाअनुसार चलिरहेको छ"],
  ["homeNeedsYou", "Needs you", "तपाईंको काम"],
  ["quoteWhereTo", "Where is your cargo going?", "तपाईंको कार्गो कहाँ जाँदैछ?"],
  ["quoteTitle", "Get a quote", "कोटेसन माग्नुहोस्"],
  ["quoteFrom", "From", "कहाँबाट"],
  ["quoteFromHint", "Pickup city, port or border", "उठाउने सहर, बन्दरगाह वा नाका"],
  ["quoteTo", "To", "कहाँसम्म"],
  ["quoteToHint", "Where it should arrive", "कहाँ पुग्नुपर्छ"],
  ["quoteYourRoutes", "Your routes", "तपाईंका रुटहरू"],
  ["quoteModeTitle", "How should it travel?", "कसरी ढुवानी गर्ने?"],
  ["quoteModeRoad", "Road", "सडक"],
  ["quoteModeRoadDetail", "Overland, through the India and China borders", "भारत र चीन नाका हुँदै स्थलमार्ग"],
  ["quoteModeSea", "Sea", "समुद्री"],
  ["quoteModeSeaDetail", "Via Kolkata, Haldia or Vizag, for the largest loads", "कोलकाता, हल्दिया वा विशाखापत्तनम हुँदै, ठूला मालका लागि"],
  ["quoteModeAir", "Air", "हवाई"],
  ["quoteModeAirDetail", "Fastest, into Kathmandu (TIA)", "सबैभन्दा छिटो, काठमाडौं (TIA) सम्म"],
  ["quoteModeUnsure", "Let KCPL advise", "KCPL लाई सल्लाह दिन दिनुहोस्"],
  ["quoteModeUnsureDetail", "We will suggest the best way for your cargo", "तपाईंको कार्गोका लागि उत्तम उपाय हामी सुझाउनेछौं"],
  ["quoteCargoTitle", "Cargo", "कार्गो"],
  ["quoteCargoHint", "What is it? Garments, machinery…", "के हो? कपडा, मेसिनरी…"],
  ["quoteWeightHint", "Weight (optional)", "तौल (ऐच्छिक)"],
  ["quoteWhenTitle", "When", "कहिले"],
  ["quoteWhenSoon", "As soon as possible", "सकेसम्म छिटो"],
  ["quoteWhenWeeks", "Within 2 weeks", "२ हप्ताभित्र"],
  ["quoteWhenMonth", "This month", "यो महिना"],
  ["quoteWhenFlexible", "Flexible", "लचिलो"],
  ["quoteNotesTitle", "Anything else", "अरू केही"],
  ["quoteNotesHint", "Dimensions, packaging, Incoterms, special handling", "नाप, प्याकेजिङ, इन्कोटर्म्स, विशेष ह्यान्डलिङ"],
  ["quoteSubmit", "Request quote", "कोटेसन माग्नुहोस्"],
  ["quoteSending", "Sending…", "पठाउँदै…"],
  ["quoteNeedsRoute", "Add where it is coming from and going to.", "कहाँबाट र कहाँसम्म भन्ने थप्नुहोस्।"],
  ["quoteSentTitle", "Quote requested", "कोटेसन माग गरियो"],
  ["quoteSentBody", "KCPL will reply with a price for {route}.", "KCPL ले {route} को मूल्य पठाउनेछ।"],
  ["quoteDone", "Done", "सकियो"],
  ["continueWithApple", "Continue with Apple", "Apple बाट जारी राख्नुहोस्"],
  ["continueWithGoogle", "Continue with Google", "Google बाट जारी राख्नुहोस्"],
  ["signInWithEmail", "Sign in with email", "इमेलबाट साइन इन गर्नुहोस्"],
  ["orWithEmail", "or with your email", "वा आफ्नो इमेलबाट"],
  ["linkProvider", "This email already has a KCPL password. Sign in with it once and {provider} will be connected for next time.", "यो इमेलमा पहिले नै KCPL पासवर्ड छ। एक पटक त्यसबाट साइन इन गर्नुहोस्, अर्को पटकका लागि {provider} जोडिनेछ।"],
  ["providerOff", "{provider} sign-in is not switched on for KCPL yet. Use your email and password.", "KCPL मा {provider} साइन इन अझै सुरु गरिएको छैन। आफ्नो इमेल र पासवर्ड प्रयोग गर्नुहोस्।"],
  ["sendDocTitle", "Send a document", "कागजात पठाउनुहोस्"],
  ["sendDocKind", "What is it?", "यो के हो?"],
  ["sendDocFile", "The document", "कागजात"],
  ["sendDocFor", "For {reference}", "{reference} का लागि"],
  ["captureTakePhoto", "Take photo", "फोटो खिच्नुहोस्"],
  ["captureChoosePhoto", "Choose photo", "फोटो छान्नुहोस्"],
  ["captureChooseFile", "Choose file", "फाइल छान्नुहोस्"],
  ["captureReplace", "Replace", "बदल्नुहोस्"],
  ["captureCameraDenied", "KCPL can't use the camera. Allow it in your phone's Settings.", "KCPL ले क्यामेरा प्रयोग गर्न सक्दैन। फोनको सेटिङमा अनुमति दिनुहोस्।"],
  ["captureUnsupported", "Send a PDF, JPEG, PNG or WEBP file.", "PDF, JPEG, PNG वा WEBP फाइल पठाउनुहोस्।"],
  ["captureTooLarge", "Files must be {size} MB or smaller.", "फाइल {size} MB वा सोभन्दा सानो हुनुपर्छ।"],
  ["captureHint", "Lay the paper flat in good light, with all four corners in view.", "कागज समतल राखी राम्रो उज्यालोमा चारै कुना देखिने गरी खिच्नुहोस्।"],
  ["sendToKcpl", "Send to KCPL", "KCPL लाई पठाउनुहोस्"],
  ["sending", "Sending…", "पठाउँदै…"],
  ["sendingPercent", "Sending… {percent}%", "पठाउँदै… {percent}%"],
  ["sendDocFootnote", "KCPL checks every document before it counts. Bills of lading, customs entries and proofs of delivery are filed by KCPL.", "KCPL ले जाँचेपछि मात्र कागजात मान्य हुन्छ। बिल अफ लेडिङ, भन्सार प्रविष्टि र डेलिभरी प्रमाण KCPL आफैँ राख्छ।"],
  ["sentTitle", "Sent to KCPL", "KCPL लाई पठाइयो"],
  ["sendChooseKind", "Choose what the document is.", "कागजात के हो छान्नुहोस्।"],
  ["sendChooseFile", "Add a photo or a file first.", "पहिले फोटो वा फाइल थप्नुहोस्।"],
  ["sendAction", "Send", "पठाउनुहोस्"],
  ["confirmPrompt", "Has it arrived?", "सामान आइपुग्यो?"],
  ["confirmPromptBody", "Let KCPL know the cargo reached you.", "सामान तपाईंकहाँ आइपुगेको KCPL लाई जानकारी दिनुहोस्।"],
  ["confirmTitle", "Confirm receipt", "प्राप्ति पुष्टि गर्नुहोस्"],
  ["confirmReceivedBy", "Received by", "बुझ्ने व्यक्ति"],
  ["confirmReceivedByHint", "Who took delivery", "सामान बुझ्ने व्यक्तिको नाम"],
  ["confirmNote", "Anything KCPL should know", "KCPL लाई थाहा हुनुपर्ने कुरा"],
  ["confirmNoteHint", "Condition, missing pieces, damage…", "अवस्था, नपुगेका टुक्रा, क्षति…"],
  ["confirmPhoto", "Photo of the delivery", "डेलिभरीको फोटो"],
  ["confirmPhotoOptional", "Optional. It is filed on the shipment for KCPL to see.", "ऐच्छिक। यो KCPL ले हेर्न ढुवानीमा राखिन्छ।"],
  ["confirmFootnote", "This tells KCPL the cargo arrived. It isn't a proof of delivery: KCPL still files that.", "यसले सामान आइपुगेको KCPL लाई जानकारी दिन्छ। यो डेलिभरी प्रमाण होइन; त्यो KCPL ले नै राख्छ।"],
  ["confirmedTitle", "Thank you", "धन्यवाद"],
  ["confirmedOn", "You confirmed receipt on {date}", "तपाईंले {date} मा प्राप्ति पुष्टि गर्नुभयो"],
  ["confirmedBy", "Received by {name}", "बुझ्ने: {name}"],
  ["receiptSend", "Send payment receipt", "भुक्तानी रसिद पठाउनुहोस्"],
  ["receiptTitle", "Payment receipt", "भुक्तानी रसिद"],
  ["receiptFile", "Bank receipt or advice", "बैंक रसिद वा सूचना"],
  ["receiptAmount", "Amount paid", "तिरेको रकम"],
  ["receiptPaidOn", "Paid on", "तिरेको मिति"],
  ["receiptNote", "Note for KCPL accounts", "KCPL लेखाका लागि टिप्पणी"],
  ["receiptNoteHint", "Bank, reference number…", "बैंक, सन्दर्भ नम्बर…"],
  ["receiptFootnote", "KCPL accounts match every receipt with the bank before the invoice changes.", "बिल परिवर्तन हुनुअघि KCPL लेखाले हरेक रसिद बैंकसँग मिलाउँछ।"],
  ["receiptsTitle", "Receipts you sent", "तपाईंले पठाएका रसिद"],
  ["receiptWithAccounts", "With KCPL accounts", "KCPL लेखामा"],
  ["receiptAcknowledged", "Acknowledged", "स्वीकार गरियो"],
  ["receiptInvalidAmount", "Enter the amount as a number.", "रकम अङ्कमा लेख्नुहोस्।"],
  ["receiptPaidOnDate", "Paid {date}", "{date} मा तिरेको"],
  ["teamTitle", "Team", "टोली"],
  ["teamInvite", "Invite a colleague", "सहकर्मीलाई निम्तो दिनुहोस्"],
  ["teamInviteBody", "They'll see your shipments and documents. Invoices stay with account owners.", "उहाँले तपाईंका ढुवानी र कागजात हेर्न सक्नुहुन्छ। बिल खाता मालिकसँग मात्र रहन्छ।"],
  ["teamSendInvite", "Send invitation", "निम्तो पठाउनुहोस्"],
  ["teamInvited", "Invitation sent", "निम्तो पठाइयो"],
  ["teamInviteSentBody", "{email} will get an email to set a password.", "{email} ले पासवर्ड राख्न इमेल पाउनुहुनेछ।"],
  ["teamInviteLinkBody", "Email isn't set up for KCPL yet, so pass this link to {email} yourself. It works once.", "KCPL को इमेल अझै सेटअप छैन, त्यसैले यो लिङ्क {email} लाई आफैँ पठाउनुहोस्। यो एक पटक मात्र चल्छ।"],
  ["teamShareLink", "Share link", "लिङ्क सेयर गर्नुहोस्"],
  ["teamStateActive", "Active", "सक्रिय"],
  ["teamStateInvited", "Invited", "निम्तो पठाइएको"],
  ["teamStateOff", "Turned off", "बन्द"],
  ["teamStateLinked", "Linked by KCPL", "KCPL ले जोडेको"],
  ["teamYou", "You", "तपाईं"],
  ["teamLastSeen", "Last signed in {date}", "अन्तिम साइन इन {date}"],
  ["teamNeverSignedIn", "Hasn't signed in yet", "अहिलेसम्म साइन इन गर्नुभएको छैन"],
  ["teamTurnOff", "Turn off login", "लगइन बन्द गर्नुहोस्"],
  ["teamTurnOn", "Turn login back on", "लगइन फेरि खोल्नुहोस्"],
  ["teamTurnOffBody", "{email} won't be able to sign in until you turn it back on.", "तपाईंले फेरि नखोलेसम्म {email} ले साइन इन गर्न सक्नुहुने छैन।"],
  ["cancel", "Cancel", "रद्द गर्नुहोस्"],
  ["teamFootnote", "Members see shipments and documents. Only KCPL can add another account owner.", "सदस्यले ढुवानी र कागजात हेर्न सक्छन्। अर्को खाता मालिक KCPL ले मात्र थप्न सक्छ।"],
  ["teamLinkedFootnote", "A login linked by KCPL belongs to another account. Ask KCPL to remove it.", "KCPL ले जोडेको लगइन अर्को खाताको हो। हटाउन KCPL लाई भन्नुहोस्।"],
  ["offlineAsOf", "Offline · as of {time}", "अफलाइन · {time} सम्मको"],
  ["lockSection", "Privacy", "गोपनीयता"],
  ["lockRequire", "Require {method}", "{method} आवश्यक"],
  ["lockFootnote", "KCPL asks for {method} when you come back to it after a minute away, and hides its content in the app switcher.", "एक मिनेटभन्दा बढी बाहिर रहेर फर्कंदा KCPL ले {method} माग्छ, र एप स्विचरमा विवरण लुकाउँछ।"],
  ["lockTitle", "KCPL is locked", "KCPL लक छ"],
  ["lockUnlock", "Unlock", "खोल्नुहोस्"],
  ["lockReason", "Unlock your KCPL account", "आफ्नो KCPL खाता खोल्नुहोस्"],
  ["lockFaceId", "Face ID", "Face ID"],
  ["lockTouchId", "Touch ID", "Touch ID"],
  ["lockFingerprint", "fingerprint", "औंठाछाप"],
  ["lockPasscode", "your passcode", "पासकोड"],
  ["shareStatus", "Share status", "स्थिति सेयर गर्नुहोस्"],
  ["shareExpected", "Expected {date}", "अपेक्षित मिति {date}"],
  ["shareDeliveredOn", "Delivered {date}", "{date} मा डेलिभर भयो"],
  ["shareFooter", "Kapileshwor Cargo · shared from the KCPL app", "कपिलेश्वर कार्गो · KCPL एपबाट सेयर गरिएको"],
  ["shareCarrierRef", "Carrier reference {reference}", "ढुवानी कम्पनीको सन्दर्भ {reference}"],
  // Quotes
  ["quotesTitle", "Quotes", "कोटेशन"],
  ["quotesNew", "New request", "नयाँ अनुरोध"],
  ["quoteValidUntil", "Valid until {date}", "{date} सम्म मान्य"],
  ["quoteExpired", "Expired {date}", "{date} मा म्याद सकियो"],
  ["quoteAsked", "You asked to proceed", "तपाईंले अघि बढ्न भन्नुभयो"],
  ["quoteBooked", "Booked as {reference}", "{reference} को रूपमा बुक भयो"],
  ["quotePriceFor", "{cargo}", "{cargo}"],
  ["quoteProceedNote", "Anything for your account manager (optional)", "खाता प्रबन्धकलाई केही भन्नु छ भने (ऐच्छिक)"],
  ["quoteProceedFootnote", "Your account manager confirms the booking with you. Nothing is booked or charged until they do.", "खाता प्रबन्धकले तपाईंसँग बुकिङ पक्का गर्नुहुन्छ। त्यसअघि केही बुक वा शुल्क लाग्दैन।"],
  ["quoteProceedDone", "Request sent", "अनुरोध पठाइयो"],
  ["quoteCargo", "Cargo", "माल"],
  ["quoteWeight", "Weight", "तौल"],
  ["quoteExpiredBody", "This price has expired. Ask KCPL for a fresh quote.", "यो मूल्यको म्याद सकियो। KCPL सँग नयाँ कोटेशन माग्नुहोस्।"],
  // Paying online
  ["payOnline", "Pay online", "अनलाइन भुक्तानी"],
  ["payChoose", "Pay {amount} with", "{amount} यसबाट तिर्नुहोस्"],
  ["payFootnote", "You pay on the gateway's own page. KCPL checks the payment with the gateway before applying it to this invoice.", "भुक्तानी गेटवेकै पेजमा हुन्छ। यो बिलमा लगाउनुअघि KCPL ले गेटवेसँग भुक्तानी जाँच गर्छ।"],
  ["payWaiting", "Finish paying in the browser", "ब्राउजरमा भुक्तानी पूरा गर्नुहोस्"],
  ["payWaitingBody", "Come back here when you're done. This page checks with KCPL on its own.", "सकिएपछि यहाँ फर्कनुहोस्। यो पेजले आफैँ KCPL सँग जाँच्छ।"],
  ["payOpenAgain", "Open the payment page again", "भुक्तानी पेज फेरि खोल्नुहोस्"],
  ["payPaid", "Payment received", "भुक्तानी प्राप्त भयो"],
  ["payPaidBody", "{amount} was applied to {invoice}.", "{amount} {invoice} मा लगाइयो।"],
  ["payReview", "Payment received", "भुक्तानी प्राप्त भयो"],
  ["payReviewBody", "KCPL accounts will apply it to {invoice} and confirm.", "KCPL लेखाले यसलाई {invoice} मा लगाएर पुष्टि गर्नेछ।"],
  ["payFailed", "Payment not completed", "भुक्तानी पूरा भएन"],
  ["payFailedBody", "Nothing was charged by KCPL. You can try again or pay another way.", "KCPL ले कुनै शुल्क लिएको छैन। फेरि प्रयास गर्नुहोस् वा अर्को तरिकाले तिर्नुहोस्।"],
  ["payOwed", "{amount} owed", "{amount} बाँकी", { amount: "String" }],
  ["payWhole", "Whole balance", "पूरा बाँकी"],
  ["payPart", "Part of it", "केही भाग"],
  ["payAmount", "Amount to pay ({currency})", "तिर्ने रकम ({currency})", { currency: "String" }],
  ["payTooMuch", "That is more than is owed.", "यो बाँकीभन्दा बढी हो।"],
  ["payTooLittle", "The smallest online payment is NPR {minimum}.", "अनलाइन सबैभन्दा सानो भुक्तानी रु. {minimum} हो।", { minimum: "int" }],
  ["payEnterAmount", "Enter an amount.", "रकम लेख्नुहोस्।"],
  ["payInRupees", "You pay {amount} in rupees", "तपाईं रुपैयाँमा {amount} तिर्नुहुन्छ", { amount: "String" }],
  ["payRate", "1 {currency} = NPR {rate}, Nepal Rastra Bank's selling rate for {date}. The rate is fixed when you start paying; KCPL accounts apply the payment to the invoice.", "१ {currency} = रु. {rate}, {date} को नेपाल राष्ट्र बैंकको बिक्री दर। भुक्तानी सुरु गर्दा दर तय हुन्छ; KCPL लेखाले भुक्तानी बिलमा लगाउँछ।", { currency: "String", rate: "String", date: "String" }],
  ["payPartFootnote", "The rest stays on the invoice, to pay later or by bank transfer.", "बाँकी रकम बिलमै रहन्छ, पछि वा बैंक ट्रान्सफरबाट तिर्न सकिन्छ।"],
  ["payCouldNotOpen", "The payment page could not be opened on this phone.", "यो फोनमा भुक्तानी पेज खुल्न सकेन।"],
  // Notifications by email
  ["emailSection", "Email me about", "यसबारे इमेल गर्नुहोस्"],
  // Calendar
  ["calendarSection", "Dates", "मिति"],
  ["calendarGregorian", "Gregorian (AD)", "ईस्वी संवत् (AD)"],
  ["calendarBikramSambat", "Bikram Sambat (BS)", "विक्रम संवत् (BS)"],
  ["calendarFootnote", "How dates show in the app. Carrier and customs papers keep their own dates.", "एपमा मिति कसरी देखिने। ढुवानी र भन्सारका कागजातमा आफ्नै मिति रहन्छ।"],
  // Tracking links
  ["trackShareLink", "Share a tracking link", "ट्र्याकिङ लिङ्क सेयर गर्नुहोस्"],
  ["trackShareLinkHint", "Anyone with the link can follow this shipment for 30 days, without a login.", "लिङ्क भएका जोकोहीले लगइनबिना ३० दिनसम्म यो ढुवानी हेर्न सक्छन्।"],
  ["trackShareMessage", "Follow {reference} with Kapileshwor Cargo: {url}", "कपिलेश्वर कार्गोमा {reference} हेर्नुहोस्: {url}"],
  ["trackStopSharing", "Stop sharing links", "लिङ्क सेयर गर्न बन्द गर्नुहोस्"],
  ["trackStopped", "Links for {reference} no longer work.", "{reference} का लिङ्क अब चल्दैनन्।"],
  ["trackStoppedNone", "There were no links to stop.", "बन्द गर्नुपर्ने कुनै लिङ्क थिएन।"],
  // Live Activity
  ["liveFollow", "Follow on Lock Screen", "लक स्क्रिनमा हेर्नुहोस्"],
  ["liveFollowAndroid", "Follow in notifications", "सूचनामा हेर्नुहोस्"],
  ["liveFollowingAndroid", "Following in your notifications", "तपाईंको सूचनामा देखिँदैछ"],
  ["liveUnavailableAndroid", "Notifications are turned off for KCPL in Settings.", "सेटिङमा KCPL को सूचना बन्द छ।"],
  ["liveChannel", "Shipment progress", "ढुवानीको प्रगति"],
  ["liveFollowing", "On your Lock Screen", "लक स्क्रिनमा छ"],
  ["liveStop", "Stop following", "हेर्न बन्द गर्नुहोस्"],
  ["liveUnavailable", "Live Activities are turned off for KCPL in Settings.", "सेटिङमा KCPL का लागि Live Activities बन्द छन्।"],
  // Scanning documents
  ["captureScan", "Scan document", "कागजात स्क्यान गर्नुहोस्"],
  // Messages on a shipment
  ["msgRow", "Message KCPL", "KCPL लाई सन्देश"],
  ["msgRowHint", "About this shipment, to the person handling it", "यो ढुवानीबारे, हेर्ने व्यक्तिलाई"],
  ["msgTitle", "Messages", "सन्देश"],
  ["msgPlaceholder", "Write a message", "सन्देश लेख्नुहोस्"],
  ["msgSend", "Send", "पठाउनुहोस्"],
  ["msgEmpty", "No messages yet", "अहिलेसम्म कुनै सन्देश छैन"],
  ["msgEmptyBody", "Ask anything about this shipment. The person handling it replies here and on the web.", "यो ढुवानीबारे जे पनि सोध्नुहोस्। हेर्ने व्यक्तिले यहीँ र वेबमा जवाफ दिनुहुन्छ।"],
  ["msgYou", "You", "तपाईं"],
  ["opsMsgRow", "Messages with the customer", "ग्राहकसँगका सन्देश"],
  ["opsMsgEmptyBody", "When the customer asks about this shipment, it appears here and on the Job File.", "ग्राहकले यो ढुवानीबारे सोधेमा यहाँ र जब फाइलमा देखिन्छ।"],
  ["opsMsgFootnote", "The customer sees your first name on replies.", "ग्राहकले जवाफमा तपाईंको पहिलो नाम देख्नुहुन्छ।"],
  // Rating a delivery
  ["rateTitle", "How did this delivery go?", "यो डेलिभरी कस्तो रह्यो?"],
  ["rateHint", "One tap. It goes to the team that handled it.", "एक ट्याप। यो काम गर्ने टोलीकहाँ पुग्छ।"],
  ["rateScore", "{score} out of 5", "५ मा {score}", { score: "int" }],
  ["rateComment", "Anything we should know? (optional)", "हामीले थाहा पाउनुपर्ने केही? (ऐच्छिक)"],
  ["rateSend", "Send rating", "मूल्याङ्कन पठाउनुहोस्"],
  ["rateThanks", "Thank you", "धन्यवाद"],
  ["rateReview", "Leave a public review", "सार्वजनिक समीक्षा लेख्नुहोस्"],
  ["rateRated", "You rated this delivery {score} out of 5", "तपाईंले यो डेलिभरीलाई ५ मा {score} दिनुभयो", { score: "int" }],
  // Estimators
  ["estStorageRow", "What will storage cost?", "भण्डारण शुल्क कति लाग्छ?"],
  ["estStorageTitle", "Storage charges", "भण्डारण शुल्क"],
  ["estDaysOver", "{days, plural, =0{Collected within free time} =1{1 day after free time} other{{days} days after free time}}", "{days, plural, =0{फ्री टाइमभित्रै उठाइयो} other{फ्री टाइमपछि {days} दिन}}", { days: "int" }],
  ["estPerDay", "{amount} a day", "प्रतिदिन {amount}", { amount: "String" }],
  ["estCollect", "{days, plural, =0{Collected today} =1{Collected tomorrow} other{Collected in {days} days}}", "{days, plural, =0{आज उठाइएमा} =1{भोलि उठाइएमा} other{{days} दिनमा उठाइएमा}}", { days: "int" }],
  ["estCharge", "Estimated charge", "अनुमानित शुल्क"],
  ["estLater", "Later", "पछि"],
  ["estSooner", "Sooner", "छिटो"],
  ["estStorageFoot", "At the daily rate KCPL recorded from the carrier. The carrier's own invoice decides the charge.", "KCPL ले क्यारियरबाट लेखेको दैनिक दरमा। शुल्क क्यारियरकै बिलले तय गर्छ।"],
  ["estNoRate", "No daily rate is recorded for this shipment yet. Ask your account manager.", "यो ढुवानीको दैनिक दर अझै लेखिएको छैन। खाता प्रबन्धकलाई सोध्नुहोस्।"],
  ["estDutyRow", "Estimate customs duty", "भन्सार महसुल अनुमान"],
  ["estDutyTitle", "Customs duty", "भन्सार महसुल"],
  ["estCif", "Value of the goods (CIF, NPR)", "सामानको मूल्य (CIF, रु.)"],
  ["estDutyRate", "Customs duty rate", "भन्सार महसुल दर"],
  ["estExcise", "Excise duty", "अन्तःशुल्क"],
  ["estNone", "None", "छैन"],
  ["estVat", "VAT at 13%", "१३% मूल्य अभिवृद्धि कर"],
  ["estLineDuty", "Customs duty", "भन्सार महसुल"],
  ["estLineExcise", "Excise duty", "अन्तःशुल्क"],
  ["estLineVat", "VAT", "मूल्य अभिवृद्धि कर"],
  ["estTotal", "Estimated total at customs", "भन्सारमा अनुमानित जम्मा"],
  ["estDutyFoot", "A rough guide from the rates you choose. The rate for your goods depends on their HS code; KCPL confirms it before clearance.", "तपाईंले छानेका दरबाट मोटामोटी अनुमान। तपाईंको सामानको दर HS कोडअनुसार हुन्छ; जाँचपासअघि KCPL ले पक्का गर्छ।"],
  // Home screen shortcuts
  ["sheetGrabber", "Show more or less of the list", "सूची धेरै वा थोरै देखाउनुहोस्"],
  ["splitShipment", "Choose a shipment", "ढुवानी छान्नुहोस्"],
  ["splitShipmentBody", "Its journey, documents and messages open here.", "यसको यात्रा, कागजात र सन्देश यहाँ खुल्छन्।"],
  ["splitInvoice", "Choose an invoice", "बिल छान्नुहोस्"],
  ["splitInvoiceBody", "Its balance, receipts and paying online open here.", "यसको बाँकी, रसिद र अनलाइन भुक्तानी यहाँ खुल्छन्।"],
  ["opsSplitJob", "Choose a job", "जब छान्नुहोस्"],
  ["opsSplitJobBody", "Its tasks, delivery and messages open here.", "यसका काम, डेलिभरी र सन्देश यहाँ खुल्छन्।"],
  ["splitDocument", "Choose a document", "कागजात छान्नुहोस्"],
  ["splitDocumentBody", "It opens here, with the shipment it belongs to.", "यो यहाँ खुल्छ, यसको ढुवानीसँगै।"],
  ["splitAccount", "Quotes and your team", "कोटेशन र तपाईंको टोली"],
  ["splitAccountBody", "They open here, beside your settings.", "यी यहाँ, तपाईंको सेटिङसँगै खुल्छन्।"],
  ["opsSplitAlert", "Choose an alert", "सूचना छान्नुहोस्"],
  ["opsSplitAlertBody", "The job it is about opens here.", "यो जुन जबबारे हो, त्यो यहाँ खुल्छ।"],
  ["docOpen", "Open", "खोल्नुहोस्"],
  ["docFile", "File", "फाइल"],
  ["docAdded", "Added", "थपिएको"],
  ["docSize", "Size", "आकार"],
  ["docState", "Review", "जाँच"],
  ["docShipment", "Open shipment {reference}", "ढुवानी {reference} खोल्नुहोस्", { reference: "String" }],
  ["docPreviewFailed", "The preview could not be loaded. Open the file instead.", "पूर्वावलोकन खुल्न सकेन। बरु फाइल खोल्नुहोस्।"],
  ["qaTrack", "Track a shipment", "ढुवानी हेर्नुहोस्"],
  ["qaQuote", "Request a quote", "कोटेशन माग्नुहोस्"],
  ["qaPay", "Pay an invoice", "बिल तिर्नुहोस्"],
  // KCPL Ops
  ["opsSignInTitle", "KCPL Operations", "KCPL अपरेसन"],
  ["opsSignInSubtitle", "Jobs, tasks and alerts across your branches.", "तपाईंका शाखाका काम, कार्य र सूचना।"],
  ["opsPriorityStandard", "Standard", "सामान्य"],
  ["opsPriorityHigh", "High", "उच्च"],
  ["opsPriorityUrgent", "Urgent", "अत्यावश्यक"],
  ["opsJustNow", "just now", "भर्खरै"],
  ["opsNoDueDate", "No due date", "म्याद छैन"],
  ["opsYours", "Yours", "तपाईंको"],
  ["opsUnassigned", "Unassigned", "कसैलाई तोकिएको छैन"],
  ["opsAlerts", "Alerts", "सूचना"],
  ["opsAllCaughtUp", "All caught up", "सबै हेरिसकियो"],
  ["opsAlertsEmpty", "Alerts for your branches and jobs appear here.", "तपाईंका शाखा र कामका सूचना यहाँ देखिन्छन्।"],
  ["opsOutForDelivery", "Out for delivery", "डेलिभरीमा निस्कियो"],
  ["opsStartDelivery", "Start delivery", "डेलिभरी सुरु गर्नुहोस्"],
  ["opsTakenBy", "Taken by", "लैजाने"],
  ["opsDriverHint", "Driver or field staff", "चालक वा फिल्ड कर्मचारी"],
  ["opsVehicleHint", "Vehicle number (optional)", "गाडी नम्बर (ऐच्छिक)"],
  ["opsStartFootnote", "Starts attempt now and shows it on the Job File and to the customer as out for delivery.", "अहिले प्रयास सुरु हुन्छ, र जब फाइल तथा ग्राहकलाई डेलिभरीमा निस्केको देखिन्छ।"],
  ["opsRelConsignee", "Consignee", "प्रापक"],
  ["opsRelStaff", "Their staff", "उहाँका कर्मचारी"],
  ["opsRelSecurity", "Security", "सुरक्षा गार्ड"],
  ["opsRelFamily", "Family", "परिवार"],
  ["opsRelOther", "Other", "अन्य"],
  ["opsRecipient", "Recipient", "प्रापक"],
  ["opsNeedRecipient", "Who received it? Enter their name.", "कसले बुझ्नुभयो? नाम लेख्नुहोस्।"],
  ["opsNeedProof", "Add a signature or a photo as proof of delivery.", "डेलिभरीको प्रमाणका लागि हस्ताक्षर वा फोटो थप्नुहोस्।"],
  ["opsNeedReason", "Say why it could not be delivered.", "किन डेलिभर हुन सकेन, लेख्नुहोस्।"],
  ["opsSavedOnPhone", "Saved on this phone", "यो फोनमा सुरक्षित भयो"],
  ["opsSavedDeliveryBody", "No signal. The delivery and its proof go to KCPL by themselves, with the time they happened, as soon as there is signal.", "सिग्नल छैन। सिग्नल आउनेबित्तिकै डेलिभरी र प्रमाण भएकै समयसहित आफैँ KCPL मा जान्छन्।"],
  ["opsProofSent", "Proof sent", "प्रमाण पठाइयो"],
  ["opsDeliveryRecorded", "Delivery recorded", "डेलिभरी दर्ता भयो"],
  ["opsAttemptRecorded", "Attempt recorded", "प्रयास दर्ता भयो"],
  ["opsSendProof", "Send proof of delivery", "डेलिभरीको प्रमाण पठाउनुहोस्"],
  ["opsRecordDelivery", "Record delivery", "डेलिभरी दर्ता गर्नुहोस्"],
  ["opsRecordAttempt", "Record attempt", "प्रयास दर्ता गर्नुहोस्"],
  ["opsProofOfDelivery", "Proof of delivery", "डेलिभरीको प्रमाण"],
  ["opsDelivery", "Delivery", "डेलिभरी"],
  ["opsDelivered", "Delivered", "डेलिभर भयो"],
  ["opsNotDelivered", "Not delivered", "डेलिभर भएन"],
  ["opsRefused", "Refused", "अस्वीकार गरियो"],
  ["opsWhere", "Where", "कहाँ"],
  ["opsProofFootnote", "Evidence reaches the desk as received. Verifying it, and marking the shipment Delivered, stays with the desk.", "प्रमाण डेस्कमा 'प्राप्त' भएर पुग्छ। त्यसको जाँच र ढुवानीलाई डेलिभर भएको मान्ने काम डेस्ककै हो।"],
  ["opsExceptionFootnote", "Opens an exception on the job for the desk.", "डेस्कका लागि काममा समस्या खुल्छ।"],
  ["opsReceivedByHeader", "Received by", "बुझ्ने"],
  ["opsFullName", "Full name", "पूरा नाम"],
  ["opsPhoneOptional", "Phone (optional)", "फोन (ऐच्छिक)"],
  ["opsRelationHint", "Relation to the consignee", "प्रापकसँगको नाता"],
  ["opsProof", "Proof", "प्रमाण"],
  ["opsGetSignature", "Get a signature", "हस्ताक्षर लिनुहोस्"],
  ["opsSigned", "Signed", "हस्ताक्षर भयो"],
  ["opsSignAgain", "Tap to sign again", "फेरि हस्ताक्षर गर्न थिच्नुहोस्"],
  ["opsPhotographDelivery", "Photograph the delivery", "डेलिभरीको फोटो खिच्नुहोस्"],
  ["opsAnotherPhoto", "Add another photo", "अर्को फोटो थप्नुहोस्"],
  ["opsPhotoHint", "The cargo at the door, a stamped delivery note", "ढोकामा सामान, छाप लागेको डेलिभरी नोट"],
  ["opsWhyRefused", "Why it was refused", "किन अस्वीकार गरियो"],
  ["opsWhyNotDelivered", "Why it could not be delivered", "किन डेलिभर हुन सकेन"],
  ["opsRefusedHint", "Damaged carton, wrong goods, not ordered…", "कार्टुन बिग्रिएको, गलत सामान, अर्डर नगरेको…"],
  ["opsFailedHint", "Nobody at the address, gate closed, road blocked…", "ठेगानामा कोही छैन, गेट बन्द, बाटो अवरुद्ध…"],
  ["opsRemovePhoto", "Remove photo", "फोटो हटाउनुहोस्"],
  ["opsLocating", "Finding where you are…", "तपाईं कहाँ हुनुहुन्छ, खोज्दै…"],
  ["opsNoLocation", "Location not available", "स्थान उपलब्ध छैन"],
  ["opsLocation", "Location", "स्थान"],
  ["opsLocationHint", "Turn on location and tap to try again. The delivery can be recorded without it.", "लोकेसन खोलेर फेरि थिच्नुहोस्। यसबिना पनि डेलिभरी दर्ता गर्न सकिन्छ।"],
  ["opsTodaysDeliveries", "Today’s deliveries", "आजका डेलिभरी"],
  ["opsMapsFailed", "Maps could not be opened on this phone.", "यो फोनमा नक्सा खुल्न सकेन।"],
  ["opsDeliveryOpenFailed", "The delivery could not be opened. Try again.", "डेलिभरी खुल्न सकेन। फेरि प्रयास गर्नुहोस्।"],
  ["opsNoDeliveriesMine", "No deliveries for you today", "आज तपाईंका डेलिभरी छैनन्"],
  ["opsNoDeliveries", "No deliveries today", "आज कुनै डेलिभरी छैन"],
  ["opsDeliveriesEmpty", "Deliveries under way or due out today in your branches appear here.", "तपाईंका शाखामा चलिरहेका वा आज निस्कने डेलिभरी यहाँ देखिन्छन्।"],
  ["opsRoute", "Route", "रुट"],
  ["opsRouteFootnote", "Hold the handle and drag to put stops in the order you will drive them. The order is kept for today.", "ह्यान्डल समातेर तान्दै स्टपलाई जाने क्रममा मिलाउनुहोस्। यो क्रम आजभरि रहन्छ।"],
  ["opsRecordedWaiting", "Recorded · waiting for signal", "दर्ता भयो · सिग्नल पर्खँदै"],
  ["opsReadyToGo", "Ready to go", "जान तयार"],
  ["opsDirections", "Directions", "बाटो"],
  ["opsRecord", "Record", "दर्ता"],
  ["opsStart", "Start", "सुरु"],
  ["opsNoteSavedOffline", "No signal. Saved on this phone; it goes to the job by itself.", "सिग्नल छैन। यो फोनमा सुरक्षित भयो; आफैँ काममा जान्छ।"],
  ["opsNeedNote", "Write a note or add a photo.", "नोट लेख्नुहोस् वा फोटो थप्नुहोस्।"],
  ["opsAddToJob", "Add to job", "काममा थप्नुहोस्"],
  ["opsNoteHint", "What did you see? Seal, damage, who you spoke to…", "के देख्नुभयो? सिल, क्षति, कोसँग कुरा भयो…"],
  ["opsPhoto", "Photo", "फोटो"],
  ["opsPhotoFiled", "Filed in the job’s Document Vault for review.", "जाँचका लागि कामको कागजात भण्डारमा राखिन्छ।"],
  ["opsFileAs", "File it as", "यसरी राख्नुहोस्"],
  ["opsNoteFootnote", "Shows on the Job File timeline on the web, with your name.", "वेबको जब फाइल टाइमलाइनमा तपाईंको नामसहित देखिन्छ।"],
  ["opsSearchStaff", "Search by name or branch", "नाम वा शाखाले खोज्नुहोस्"],
  ["opsStaffFailed", "The staff list could not be loaded.", "कर्मचारी सूची लोड हुन सकेन।"],
  ["opsNobodyFound", "Nobody found", "कोही भेटिएन"],
  ["opsStaffEmpty", "Only staff who share one of your branches are listed.", "तपाईंको कुनै शाखामा काम गर्ने कर्मचारी मात्र देखिन्छन्।"],
  ["opsStaffHeader", "Staff in your branches", "तपाईंका शाखाका कर्मचारी"],
  ["opsAssignJob", "Assign job", "काम तोक्नुहोस्"],
  ["opsGiveJobTo", "Give job to", "काम यसलाई दिनुहोस्"],
  ["opsReassignFailed", "The job was not reassigned. Try again.", "काम अरूलाई दिन सकिएन। फेरि प्रयास गर्नुहोस्।"],
  ["opsDone", "Done", "भयो"],
  ["opsNeedTaskTitle", "Give the task a title.", "कार्यको शीर्षक लेख्नुहोस्।"],
  ["opsNewTask", "New task", "नयाँ कार्य"],
  ["opsTitle", "Title", "शीर्षक"],
  ["opsNotesOptional", "Notes (optional)", "नोट (ऐच्छिक)"],
  ["opsDue", "Due", "म्याद"],
  ["opsNoDate", "No date", "मिति छैन"],
  ["opsToday5pm", "Today, 5 PM", "आज, बेलुका ५ बजे"],
  ["opsTomorrow10am", "Tomorrow, 10 AM", "भोलि, बिहान १० बजे"],
  ["opsPick", "Pick…", "छान्नुहोस्…"],
  ["opsAssignedTo", "Assigned to", "जिम्मा"],
  ["opsAssignTask", "Assign task", "कार्य तोक्नुहोस्"],
  ["opsNobodyYet", "Nobody yet", "अहिलेसम्म कोही होइन"],
  ["opsBranch", "Branch", "शाखा"],
  ["opsNeedOverride", "Say why it is being closed anyway (at least 8 characters).", "जे भए पनि किन बन्द गरिँदैछ, लेख्नुहोस् (कम्तीमा ८ अक्षर)।"],
  ["opsNotClosed", "Not closed: something still stands in the way.", "बन्द भएन: अझै केही बाँकी छ।"],
  ["opsJobClosed", "Job closed", "काम बन्द भयो"],
  ["opsJobClosedBody", "The Job File is closed, with your name and the time.", "जब फाइल तपाईंको नाम र समयसहित बन्द भयो।"],
  ["opsCloseJob", "Close job", "काम बन्द गर्नुहोस्"],
  ["opsCloseAnyway", "Close anyway", "जे भए पनि बन्द गर्नुहोस्"],
  ["opsReadyToClose", "Ready to close", "बन्द गर्न तयार"],
  ["opsReadyToCloseBody", "Tasks, customs and proof of delivery are all in order.", "कार्य, भन्सार र डेलिभरीको प्रमाण सबै ठीक छन्।"],
  ["opsStillOpen", "Still open", "अझै बाँकी"],
  ["opsOverrideReason", "Reason to close anyway", "जे भए पनि बन्द गर्ने कारण"],
  ["opsOverrideHint", "Recorded on the Job File with your name", "तपाईंको नामसहित जब फाइलमा राखिन्छ"],
  ["opsCloseBlockedFootnote", "Clear these first, or ask Management to close it with a reason.", "पहिले यी सक्नुहोस्, वा व्यवस्थापनलाई कारणसहित बन्द गर्न भन्नुहोस्।"],
  ["opsJobNotFound", "Job not found", "काम भेटिएन"],
  ["opsJobNotFoundBody", "It may have been closed or moved outside your branches.", "यो बन्द भएको वा तपाईंका शाखाबाहिर सरेको हुन सक्छ।"],
  ["opsOwner", "Owner", "जिम्मेवार"],
  ["opsAssignSomeone", "Assign someone", "कसैलाई तोक्नुहोस्"],
  ["opsGiveToSomeone", "Give to someone else", "अरूलाई दिनुहोस्"],
  ["opsNoOwner", "Nobody owns this job yet.", "यो काम अझै कसैको जिम्मामा छैन।"],
  ["opsTasks", "Tasks", "कार्य"],
  ["opsNoTasks", "No tasks yet. Tasks added here or in the Job File show on both.", "अहिलेसम्म कार्य छैन। यहाँ वा जब फाइलमा थपेका कार्य दुवैतिर देखिन्छन्।"],
  ["opsCustoms", "Customs", "भन्सार"],
  ["opsRequired", "Required", "अनिवार्य"],
  ["opsOptional", "Optional", "ऐच्छिक"],
  ["opsBeforeCloseout", "Before closeout", "बन्द गर्नुअघि"],
  ["opsFromField", "From the field", "फिल्डबाट"],
  ["opsNotes", "Notes", "नोट"],
  ["opsDetails", "Details", "विवरण"],
  ["opsCustomer", "Customer", "ग्राहक"],
  ["opsPriority", "Priority", "प्राथमिकता"],
  ["opsHandling", "Handling", "ह्यान्डलिङ"],
  ["opsInternalRef", "Internal ref", "आन्तरिक सन्दर्भ"],
  ["opsProfitability", "Profitability", "नाफा"],
  ["opsRevenue", "Revenue", "आम्दानी"],
  ["opsCost", "Cost", "लागत"],
  ["opsProfit", "Profit", "नाफा"],
  ["opsMargin", "Margin", "मार्जिन"],
  ["opsJobIsClosed", "This job is closed.", "यो काम बन्द छ।"],
  ["opsCloseJobEllipsis", "Close job…", "काम बन्द गर्नुहोस्…"],
  ["opsQueuedDeliveryBody", "This delivery is on your phone and goes to KCPL, with the time it happened, as soon as there is signal.", "यो डेलिभरी तपाईंको फोनमा छ, सिग्नल आउनेबित्तिकै भएकै समयसहित KCPL मा जान्छ।"],
  ["opsDeleteDelivery", "Delete this delivery", "यो डेलिभरी मेटाउनुहोस्"],
  ["opsRecordHowItWent", "Record how it went", "कस्तो भयो, दर्ता गर्नुहोस्"],
  ["opsAddProof", "Add proof of delivery", "डेलिभरीको प्रमाण थप्नुहोस्"],
  ["opsWaitingForSignal", "Waiting for signal", "सिग्नल पर्खँदै"],
  ["opsSignature", "Signature", "हस्ताक्षर"],
  ["opsDocument", "Document", "कागजात"],
  ["opsScheduled", "Scheduled", "तालिका बनेको"],
  ["opsPodReceived", "Proof received · the desk verifies it", "प्रमाण प्राप्त · डेस्कले जाँच्छ"],
  ["opsPodVerified", "Proof of delivery verified", "डेलिभरीको प्रमाण जाँचियो"],
  ["opsPodRejected", "Proof rejected by the desk · add new proof", "डेस्कले प्रमाण अस्वीकार गर्‍यो · नयाँ प्रमाण थप्नुहोस्"],
  ["opsPodNone", "No proof of delivery yet", "अहिलेसम्म डेलिभरीको प्रमाण छैन"],
  ["opsQueuedNoteBody", "This note is on your phone and goes to the job as soon as KCPL can be reached.", "यो नोट तपाईंको फोनमा छ, KCPL सँग सम्पर्क हुनेबित्तिकै काममा जान्छ।"],
  ["opsDeleteNote", "Delete note", "नोट मेटाउनुहोस्"],
  ["opsAddNote", "Add a note or photo", "नोट वा फोटो थप्नुहोस्"],
  ["opsCouldNotOpen", "That could not be opened on this device.", "यो उपकरणमा खुल्न सकेन।"],
  ["opsChangeNotSaved", "That change was not saved. Try again.", "परिवर्तन सुरक्षित भएन। फेरि प्रयास गर्नुहोस्।"],
  ["opsMine", "Mine", "मेरा"],
  ["opsAll", "All", "सबै"],
  ["opsOverdue", "Overdue", "म्याद नाघेका"],
  ["opsExceptions", "Exceptions", "समस्या"],
  ["opsJobs", "Jobs", "काम"],
  ["opsScan", "Scan", "स्क्यान"],
  ["opsSearchJobs", "Search reference, customer, route or owner…", "सन्दर्भ, ग्राहक, रुट वा जिम्मेवार खोज्नुहोस्…"],
  ["opsNoActiveJobs", "No active jobs", "सक्रिय काम छैन"],
  ["opsNothingMatches", "Nothing matches", "केही मिलेन"],
  ["opsJobsEmpty", "Jobs in your branches appear here.", "तपाईंका शाखाका काम यहाँ देखिन्छन्।"],
  ["opsJobsNoMatch", "Try another filter or clear the search.", "अर्को फिल्टर प्रयोग गर्नुहोस् वा खोज हटाउनुहोस्।"],
  ["opsMe", "Me", "म"],
  ["opsRole", "Role", "भूमिका"],
  ["opsBranches", "Branches", "शाखा"],
  ["opsAllBranches", "All branches", "सबै शाखा"],
  ["opsCostsAndMargins", "Costs and margins", "लागत र मार्जिन"],
  ["opsVisible", "Visible", "देखिन्छ"],
  ["opsNotShared", "Not shared with this role", "यो भूमिकालाई देखाइँदैन"],
  ["opsRolesFootnote", "Roles and branch access are managed by KCPL Management in the web admin.", "भूमिका र शाखा पहुँच KCPL व्यवस्थापनले वेब एडमिनबाट मिलाउँछ।"],
  ["opsNotifications", "Notifications", "सूचना"],
  ["opsSignOut", "Sign out", "साइन आउट"],
  ["opsToday", "Today", "आज"],
  ["opsDemoBanner", "Demo data, not real operations", "नमुना डाटा, वास्तविक काम होइन"],
  ["opsReadingText", "Reading the text…", "अक्षर पढ्दै…"],
  ["opsPointAtCode", "Point at a barcode or QR code", "बारकोड वा QR कोडतिर देखाउनुहोस्"],
  ["opsScanHint", "Or read a container number off the door, or type a reference.", "वा ढोकाबाट कन्टेनर नम्बर पढ्नुहोस्, वा सन्दर्भ टाइप गर्नुहोस्।"],
  ["opsReadText", "Read text", "अक्षर पढ्नुहोस्"],
  ["opsTypeIt", "Type it", "टाइप गर्नुहोस्"],
  ["opsNoNumber", "No number in that photo", "त्यो फोटोमा नम्बर छैन"],
  ["opsTapNumber", "Tap the number to find", "खोज्ने नम्बर थिच्नुहोस्"],
  ["opsTryCloser", "Try closer, straight on, in good light.", "नजिकबाट, सिधा, राम्रो उज्यालोमा प्रयास गर्नुहोस्।"],
  ["opsCheckDigitFirst", "Container numbers that pass their check digit come first.", "चेक डिजिट मिलेका कन्टेनर नम्बर पहिले आउँछन्।"],
  ["opsScanAgain", "Scan again", "फेरि स्क्यान गर्नुहोस्"],
  ["opsLookupHint", "Job, container, B/L or AWB number", "काम, कन्टेनर, B/L वा AWB नम्बर"],
  ["opsFindJob", "Find job", "काम खोज्नुहोस्"],
  ["opsBackToCamera", "Back to camera", "क्यामेरामा फर्कनुहोस्"],
  ["opsNoMatchBody", "Only jobs in your branches can be found. Check the number, or search Jobs.", "तपाईंका शाखाका काम मात्र भेटिन्छन्। नम्बर जाँच्नुहोस्, वा कामहरूमा खोज्नुहोस्।"],
  ["opsCameraDenied", "Allow the camera for KCPL Ops in Settings to scan. You can still type a reference below.", "स्क्यान गर्न सेटिङमा KCPL Ops लाई क्यामेरा दिनुहोस्। तल सन्दर्भ टाइप गर्न सकिन्छ।"],
  ["opsCameraUnavailable", "The camera is not available. You can still type a reference below.", "क्यामेरा उपलब्ध छैन। तल सन्दर्भ टाइप गर्न सकिन्छ।"],
  ["opsCancel", "Cancel", "रद्द गर्नुहोस्"],
  ["opsClear", "Clear", "मेटाउनुहोस्"],
  ["opsSignatureArea", "Signature area. Sign with one finger.", "हस्ताक्षर गर्ने ठाउँ। एउटा औँलाले हस्ताक्षर गर्नुहोस्।"],
  ["opsNeedsAction", "Needs action", "काम गर्नुपर्ने"],
  ["opsMoving", "Moving", "गतिमा"],
  ["opsAllJobs", "All jobs", "सबै काम"],
  ["opsNothingWaiting", "Nothing waiting on you", "तपाईंलाई पर्खिरहेको केही छैन"],
  ["opsNothingWaitingBody", "No active jobs in your branches need attention right now.", "तपाईंका शाखाका कुनै सक्रिय काममा अहिले ध्यान चाहिँदैन।"],
  ["opsMinutesAgo", "{minutes} min ago", "{minutes} मिनेटअघि", {"minutes": "int"}],
  ["opsHoursAgo", "{hours} h ago", "{hours} घण्टाअघि", {"hours": "int"}],
  ["opsDaysAgo", "{days} d ago", "{days} दिनअघि", {"days": "int"}],
  ["opsOverdueDue", "Overdue · due {when}", "म्याद नाघ्यो · {when}"],
  ["opsDueToday", "Due today {time}", "आज {time} सम्म"],
  ["opsDueTomorrow", "Due tomorrow {time}", "भोलि {time} सम्म"],
  ["opsDueOn", "Due {date}", "{date} सम्म"],
  ["opsOverdueCount", "{count} overdue", "{count} म्याद नाघेका", {"count": "int"}],
  ["opsCustomsOpenCount", "{count} customs open", "{count} भन्सार बाँकी", {"count": "int"}],
  ["opsPodWithDesk", "Proof of delivery is with the desk to verify. KCPL marks {reference} Delivered once it is checked.", "डेलिभरीको प्रमाण जाँचका लागि डेस्कमा छ। जाँचपछि KCPL ले {reference} लाई डेलिभर भएको मान्छ।"],
  ["opsExceptionOpened", "The desk has an exception on {reference} to follow up and arrange the next attempt.", "डेस्कले {reference} मा समस्या हेरेर अर्को प्रयास मिलाउनेछ।"],
  ["opsSendTo", "Send to {reference}", "{reference} मा पठाउनुहोस्"],
  ["opsAttemptN", "Attempt {number}", "प्रयास {number}", {"number": "int"}],
  ["opsSignedBy", "{signer} · tap to sign again", "{signer} · फेरि हस्ताक्षर गर्न थिच्नुहोस्"],
  ["opsWithinMetres", "Within {metres} m · recorded with the delivery", "{metres} मिटरभित्र · डेलिभरीसँगै दर्ता हुन्छ", {"metres": "int"}],
  ["opsMineCount", "Mine · {count}", "मेरा · {count}", {"count": "int"}],
  ["opsAllCount", "All · {count}", "सबै · {count}", {"count": "int"}],
  ["opsDirectionsTo", "Directions to {place}", "{place} सम्मको बाटो"],
  ["opsOutForDeliveryAttempt", "Out for delivery · attempt {number}", "डेलिभरीमा निस्कियो · प्रयास {number}", {"number": "int"}],
  ["opsReorder", "Reorder {reference}", "{reference} को क्रम मिलाउनुहोस्"],
  ["opsSaveTo", "Save to {reference}", "{reference} मा सुरक्षित गर्नुहोस्"],
  ["opsNowWith", "{reference} is now with {name}.", "{reference} अब {name} को जिम्मामा छ।"],
  ["opsAddTo", "Add to {reference}", "{reference} मा थप्नुहोस्"],
  ["opsTaskFootnote", "For {branch}. Shows on the Job File and the assignee’s task list.", "{branch} का लागि। जब फाइल र जिम्मा पाउनेको कार्यसूचीमा देखिन्छ।"],
  ["opsCloseReference", "Close {reference}", "{reference} बन्द गर्नुहोस्"],
  ["opsReceivedBy", "Received by {name}", "{name} ले बुझ्नुभयो"],
  ["opsProofCount", "{count} proof", "{count} प्रमाण", {"count": "int"}],
  ["opsAttemptLabel", "Attempt {number} · {label}", "प्रयास {number} · {label}", {"number": "int"}],
  ["opsPhotoCount", "{count, plural, =1{1 photo} other{{count} photos}}", "{count} फोटो", {"count": "int"}],
  ["opsCall", "Call {name}", "{name} लाई फोन गर्नुहोस्"],
  ["opsWhatsApp", "WhatsApp {name}", "{name} लाई WhatsApp गर्नुहोस्"],
  ["opsDoneOf", "{label} · {done} of {total} done", "{label} · {total} मध्ये {done} सकियो", {"done": "int", "total": "int"}],
  ["opsVersion", "KCPL Ops {version}", "KCPL Ops {version}"],
  ["opsFinding", "Finding {query}…", "{query} खोज्दै…"],
  ["opsNoJobMatches", "No job matches {query}", "{query} सँग कुनै काम मिलेन"],
  ["opsJobsMatch", "{count} jobs match {query}", "{query} सँग {count} काम मिले", {"count": "int"}],
  ["opsDueTodaySummary", "{count} due today · your route, directions and proof", "आज {count} · तपाईंको रुट, बाटो र प्रमाण", {"count": "int"}],
  ["opsOverdueTasks", "{count, plural, =1{1 overdue task} other{{count} overdue tasks}}", "{count} म्याद नाघेका कार्य", {"count": "int"}],
  ["opsCustomsBlocks", "{count, plural, =1{1 customs block} other{{count} customs blocks}}", "{count} भन्सार अवरोध", {"count": "int"}],
  ["opsDeliveringToday", "{count} delivering today", "आज {count} डेलिभरी", {"count": "int"}],
  ["opsUnassignedCount", "{count} unassigned", "{count} तोकिएका छैनन्", {"count": "int"}],
  ["opsUrgentCount", "{count} urgent", "{count} अत्यावश्यक", {"count": "int"}],
  ["opsCustomsCount", "{count} customs", "{count} भन्सार", {"count": "int"}],
  ["opsLanguage", "Language", "भाषा"],
  ["opsSignAbove", "Sign above the line", "रेखामाथि हस्ताक्षर गर्नुहोस्"],
  ["opsPushPrimerTitle", "Get alerts as they happen", "सूचना तुरुन्तै पाउनुहोस्"],
  ["opsPushPrimerBody", "Assignments, overdue tasks, customs and exceptions for your jobs, on this phone.", "तपाईंका कामका जिम्मा, म्याद नाघेका कार्य, भन्सार र समस्या यो फोनमा।"],
  ["opsPushBlockedHelp", "Allow notifications for KCPL Ops in your phone's Settings.", "फोनको सेटिङमा KCPL Ops लाई सूचना दिन अनुमति दिनुहोस्।"],
  ["opsLanguageFootnote", "Records (references, places, notes from the desk) stay as KCPL holds them.", "रेकर्ड (सन्दर्भ, ठाउँ, डेस्कका नोट) KCPL मा जस्तो छ त्यस्तै रहन्छ।"],
];

const camel = (key) => key.replace(/[._](\w)/g, (_, c) => c.toUpperCase());

function placeholders(text, types = {}) {
  const names = [...text.matchAll(/\{(\w+)[},]/g)].map((match) => match[1]);
  return Object.fromEntries([...new Set(names)].map((name) => [name, { type: types[name] ?? "String" }]));
}

for (const locale of ["en", "ne"]) {
  const arb = { "@@locale": locale };
  const add = (name, text, types) => {
    if (name in arb) throw new Error(`duplicate ARB key ${name}`);
    arb[name] = text;
    const vars = placeholders(text, types);
    if (locale === "en" && Object.keys(vars).length) arb[`@${name}`] = { placeholders: vars };
  };
  for (const key of portalKeys) {
    const text = portalText(locale, key);
    if (text === key) throw new Error(`portal key ${key} is missing`);
    add(camel(key), text);
  }
  for (const [name, en, ne, types] of appStrings) add(name, locale === "en" ? en : ne, types);
  writeFileSync(new URL(`../lib/l10n/app_${locale}.arb`, import.meta.url), `${JSON.stringify(arb, null, 2)}\n`);
}
console.log(`wrote ${portalKeys.length + appStrings.length} strings per locale`);
