import Link from "next/link";
import { AlertTriangle, Boxes, Download, Landmark, PackageCheck, Scale, Target, UsersRound } from "lucide-react";
import type { CrmCurrency } from "../crm/crm-data";
import type { ManagementAnalytics, ManagementRangeKey, TrendPoint } from "./management-data";
import { OpsBadge, OpsMono, OpsPage, OpsPageHeader, OpsProgress, OpsStat, OpsStatStrip, OpsSurface } from "../operations-ui";

function money(amount: number, currency: string) { try { return new Intl.NumberFormat("en-AU", { style: "currency", currency, maximumFractionDigits: 2 }).format(amount); } catch { return `${currency} ${amount.toLocaleString("en-AU")}`; } }
function number(value: number) { return new Intl.NumberFormat("en-AU", { maximumFractionDigits: 0 }).format(value); }
function percentage(value: number | null) { return value === null ? "N/A" : `${value.toFixed(1)}%`; }
function queryFor(range: ManagementAnalytics["range"]) { const params = new URLSearchParams({ range: range.key }); if (range.from) params.set("from", range.from); if (range.to) params.set("to", range.to); return params.toString(); }

const ranges: Array<{ key: ManagementRangeKey; label: string }> = [
  { key: "today", label: "Today" }, { key: "7d", label: "7 days" }, { key: "month", label: "Month" }, { key: "quarter", label: "Quarter" }, { key: "year", label: "Year" }, { key: "all", label: "All time" },
];

export function ManagementWorkspace({ analytics }: { analytics: ManagementAnalytics }) {
  const exportQuery = queryFor(analytics.range);
  const topCustomers = analytics.customers.slice(0, 12);
  const topRoutes = analytics.routes.slice(0, 10);
  const lossJobs = analytics.loss_making_jobs.slice(0, 10);
  const workload = analytics.staff_workload.slice(0, 12);
  const trendCurrencies = [...new Set(analytics.trends.map((item) => item.currency))];
  const quality = analytics.data_quality;
  const dataQualityCount = quality.excluded_currency_records + quality.unassigned_branch_financial_records + quality.active_unassigned_branch_shipments + quality.unlinked_invoice_records + quality.orphaned_job_cost_records;

  return <OpsPage>
    <OpsPageHeader eyebrow="Management" title="Analytics" description="Selected-period performance beside live working-capital and operational pressure. Currencies are deliberately never blended into a fake grand total." meta={<><OpsBadge tone="accent">{analytics.range.label}</OpsBadge><span>Generated {new Intl.DateTimeFormat("en-AU", { dateStyle: "medium", timeStyle: "short" }).format(new Date(analytics.generated_at))}</span></>} actions={<><Link href={`/api/admin/management/export?${exportQuery}`} className="ops-button" data-variant="secondary" data-size="md"><Download size={13}/>Export CSV</Link><Link href="/admin/command-centre" className="ops-button" data-variant="primary" data-size="md">Operations home</Link></>}> 
      <div className="mt-5 flex flex-wrap items-end gap-2"><div className="ops-segmented">{ranges.map((item) => <Link key={item.key} href={`/admin/management?range=${item.key}`} data-active={analytics.range.key === item.key || undefined}>{item.label}</Link>)}</div><form method="get" className="flex flex-wrap items-end gap-2"><input type="hidden" name="range" value="custom"/><label className="text-[8px] font-bold uppercase tracking-[.08em] text-[#958b83]">From<input name="from" type="date" defaultValue={analytics.range.key === "custom" ? analytics.range.from ?? "" : ""} className="ops-input mt-1 block w-[145px]"/></label><label className="text-[8px] font-bold uppercase tracking-[.08em] text-[#958b83]">To<input name="to" type="date" defaultValue={analytics.range.key === "custom" ? analytics.range.to ?? "" : ""} className="ops-input mt-1 block w-[145px]"/></label><button className="ops-button" data-variant="secondary" data-size="sm">Apply</button></form></div>
    </OpsPageHeader>

    <OpsStatStrip>
      <OpsStat label="Active shipments" value={number(analytics.active_shipments)} icon={<Boxes size={13}/>} />
      <OpsStat label="Delivered" value={number(analytics.delivered_in_period)} icon={<PackageCheck size={13}/>} tone="success"/>
      <OpsStat label="Quote win rate" value={`${analytics.quote_conversion_percent.toFixed(1)}%`} icon={<Target size={13}/>} />
      <OpsStat label="Urgent / exception" value={`${analytics.urgent_shipments} / ${analytics.exception_shipments}`} icon={<AlertTriangle size={13}/>} tone={analytics.urgent_shipments + analytics.exception_shipments ? "danger" : "neutral"}/>
      <OpsStat label="Customs blocked" value={number(analytics.customs_blocked_shipments)} icon={<Scale size={13}/>} tone={analytics.customs_blocked_shipments ? "warning" : "neutral"}/>
      <OpsStat label="Unassigned" value={number(analytics.unassigned_shipments)} icon={<UsersRound size={13}/>} tone={analytics.unassigned_shipments ? "warning" : "neutral"}/>
    </OpsStatStrip>

    <div className="ops-content-wide ops-stack">
      {dataQualityCount ? <div className="ops-notice" data-tone="warning"><span><strong>Reporting integrity:</strong> {dataQualityCount} tracked records need cleanup. {quality.excluded_currency_records} unsupported-currency, {quality.unassigned_branch_financial_records} unassigned financial, {quality.active_unassigned_branch_shipments} unassigned shipments, {quality.unlinked_invoice_records} unlinked invoices, {quality.orphaned_job_cost_records} orphaned costs.</span></div> : null}

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><DecisionCard label="Quote decisions" value={`${analytics.quote_decided}/${analytics.quote_total}`} detail={`${analytics.quote_open} open · ${analytics.quote_decision_rate_percent.toFixed(1)}% decision rate`}/><DecisionCard label="Loss-making jobs" value={number(analytics.loss_making_jobs.length)} detail="Jobs financially touched in period" danger={analytics.loss_making_jobs.length > 0}/><DecisionCard label="Data quality" value={number(dataQualityCount)} detail={dataQualityCount ? "Records need cleanup" : "No tracked integrity issues"} danger={dataQualityCount > 0}/><DecisionCard label="Delivered in period" value={number(analytics.delivered_in_period)} detail={`${analytics.active_shipments} currently active`}/></div>

      <section><SectionTitle eyebrow="Money by currency" title="Period P&L + live working capital" detail="Revenue and recognised job cost follow the selected range. AR and AP are current open balances."/><div className="mt-3 grid gap-3 xl:grid-cols-2">{analytics.financials.length ? analytics.financials.map((item) => <OpsSurface key={item.currency} eyebrow={item.currency} title={`${money(item.profit, item.currency)} gross profit`} description={`${item.invoice_count} invoices · ${item.cost_item_count} recognised costs`} action={<OpsBadge tone={item.profit >= 0 ? "success" : "danger"}>{percentage(item.margin_percent)} margin</OpsBadge>}><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><MoneyMini label="Revenue" value={money(item.revenue, item.currency)}/><MoneyMini label="Cost" value={money(item.cost, item.currency)}/><MoneyMini label="AR open" value={money(item.receivables, item.currency)} warn={item.overdue_receivables > 0}/><MoneyMini label="AP open" value={money(item.payables, item.currency)} warn={item.overdue_payables > 0}/></div>{item.overdue_receivables || item.overdue_payables ? <div className="mt-3 flex flex-wrap gap-2"><OpsBadge tone="danger">Overdue AR {money(item.overdue_receivables, item.currency)}</OpsBadge><OpsBadge tone="warning">Overdue AP {money(item.overdue_payables, item.currency)}</OpsBadge></div> : null}</OpsSurface>) : <Empty text="No financial activity or live balances for this range."/>}</div></section>

      {trendCurrencies.length ? <section><SectionTitle eyebrow="Trend" title="Monthly revenue, cost & profit" detail="A compact trend view, separated by currency."/><div className="mt-3 grid gap-3 xl:grid-cols-2">{trendCurrencies.map((currency) => <TrendChart key={currency} currency={currency} points={analytics.trends.filter((item) => item.currency === currency)}/>)}</div></section> : null}

      <div className="ops-grid-2"><OpsSurface eyebrow="Branch performance" title="Where value is being created" description="Selected-period P&L by branch and currency." flush><div className="ops-table-wrap"><table className="ops-table min-w-[780px]"><thead><tr><th>Branch</th><th>Currency</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th><th>Active jobs</th></tr></thead><tbody>{analytics.branches.length ? analytics.branches.map((row) => <tr key={`${row.branch}-${row.currency}`}><td>{row.branch === "Unassigned" ? <strong className="inline-flex items-center gap-1.5"><Landmark size={11}/>{row.branch}</strong> : <Link href={`/admin/branches/${encodeURIComponent(row.branch)}`} className="inline-flex items-center gap-1.5 font-bold text-[#4f4741] hover:text-[#a65c49] hover:underline"><Landmark size={11}/>{row.branch}</Link>}</td><td>{row.currency}</td><td>{money(row.revenue,row.currency)}</td><td>{money(row.cost,row.currency)}</td><td className={row.profit < 0 ? "font-bold text-[#b65355]" : "font-bold text-[#66806b]"}>{money(row.profit,row.currency)}</td><td>{percentage(row.margin_percent)}</td><td>{row.active_jobs}</td></tr>) : <tr><td colSpan={7}><Empty text="No branch P&L in this period."/></td></tr>}</tbody></table></div></OpsSurface>
        <OpsSurface eyebrow="Concentration" title="Customer dependency" description="Revenue concentration inside each currency."><div className="space-y-4">{analytics.concentration.length ? analytics.concentration.map((risk) => <div key={risk.currency}><div className="flex items-center justify-between gap-3"><div><strong className="text-[10px] text-[#514840]">{risk.currency} · {risk.top_customer_name || "No customer"}</strong><p className="mt-1 text-[8px] text-[#9c928a]">Top five {risk.top_five_share_percent.toFixed(1)}% of {money(risk.total_revenue,risk.currency)}</p></div><OpsBadge tone={risk.top_customer_share_percent >= 40 ? "danger" : risk.top_customer_share_percent >= 25 ? "warning" : "success"}>{risk.top_customer_share_percent.toFixed(1)}% top customer</OpsBadge></div><div className="mt-2"><OpsProgress value={risk.top_customer_share_percent} max={100} tone={risk.top_customer_share_percent >= 40 ? "danger" : risk.top_customer_share_percent >= 25 ? "warning" : "success"}/></div></div>) : <Empty text="Not enough customer revenue yet."/>}</div></OpsSurface></div>

      <div className="ops-grid-2"><OpsSurface eyebrow="Customers" title="Customer profitability" description="Selected-period P&L ranked by profit within currency." flush><div className="ops-table-wrap"><table className="ops-table min-w-[720px]"><thead><tr><th>Customer</th><th>Currency</th><th>Revenue</th><th>Cost</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{topCustomers.length ? topCustomers.map((row) => <tr key={`${row.customer_id || row.customer_name}-${row.currency}`}><td><strong>{row.customer_name}</strong>{row.customer_id ? <p className="mt-1"><Link href={`/admin/crm/${encodeURIComponent(row.customer_id)}`} className="text-[8px] font-bold text-[#b5654f]">Customer 360</Link></p> : null}</td><td>{row.currency}</td><td>{money(row.revenue,row.currency)}</td><td>{money(row.cost,row.currency)}</td><td className={row.profit < 0 ? "font-bold text-[#b65355]" : "font-bold text-[#66806b]"}>{money(row.profit,row.currency)}</td><td>{percentage(row.margin_percent)}</td></tr>) : <tr><td colSpan={6}><Empty text="No customer P&L in this period."/></td></tr>}</tbody></table></div></OpsSurface>
        <OpsSurface eyebrow="Routes" title="Route economics" description="Selected-period route performance." flush><div className="ops-table-wrap"><table className="ops-table min-w-[700px]"><thead><tr><th>Route</th><th>Mode</th><th>Currency</th><th>Jobs</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{topRoutes.length ? topRoutes.map((row,index) => <tr key={`${row.origin}-${row.destination}-${row.mode}-${row.currency}-${index}`}><td><strong>{row.origin} → {row.destination}</strong></td><td>{row.mode}</td><td>{row.currency}</td><td>{row.jobs}</td><td className={row.profit < 0 ? "font-bold text-[#b65355]" : "font-bold text-[#66806b]"}>{money(row.profit,row.currency)}</td><td>{percentage(row.margin_percent)}</td></tr>) : <tr><td colSpan={6}><Empty text="No route economics in this period."/></td></tr>}</tbody></table></div></OpsSurface></div>

      <div className="ops-grid-2"><OpsSurface eyebrow="Exceptions" title="Loss-making jobs" description="Jobs with negative lifetime economics that had financial activity in the period." flush><div className="ops-table-wrap"><table className="ops-table min-w-[720px]"><thead><tr><th>Shipment</th><th>Customer</th><th>Branch</th><th>Currency</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{lossJobs.length ? lossJobs.map((job) => <tr key={`${job.shipment_reference}-${job.currency}`}><td><Link href={`/admin/jobs/${encodeURIComponent(job.shipment_reference)}`}><OpsMono>{job.shipment_reference}</OpsMono></Link></td><td>{job.customer_name}</td><td>{job.branch}</td><td>{job.currency}</td><td className="font-bold text-[#b65355]">{money(job.profit,job.currency)}</td><td className="text-[#b65355]">{percentage(job.margin_percent)}</td></tr>) : <tr><td colSpan={6}><Empty text="No loss-making jobs in the current slice."/></td></tr>}</tbody></table></div></OpsSurface>
        <OpsSurface eyebrow="People" title="Staff workload" description="Current ownership pressure, independent of the financial range." flush><div className="ops-table-wrap"><table className="ops-table min-w-[650px]"><thead><tr><th>Staff</th><th>Jobs</th><th>Tasks</th><th>Overdue</th><th>Urgent</th></tr></thead><tbody>{workload.length ? workload.map((row,index) => <tr key={`${row.staff_email || row.staff_name}-${index}`}><td>{row.staff_email ? <Link href={`/admin/workload/${encodeURIComponent(row.staff_email)}`} className="font-bold text-[#4f4741] hover:text-[#a65c49] hover:underline">{row.staff_name}</Link> : <strong>{row.staff_name}</strong>}<p className="mt-1 text-[8px] text-[#9c928a]">{row.staff_email || "No email"}</p></td><td>{row.active_jobs}</td><td>{row.open_tasks}</td><td className={row.overdue_tasks ? "font-bold text-[#b65355]" : ""}>{row.overdue_tasks}</td><td className={row.urgent_jobs ? "font-bold text-[#9a682f]" : ""}>{row.urgent_jobs}</td></tr>) : <tr><td colSpan={5}><Empty text="No staff workload yet."/></td></tr>}</tbody></table></div></OpsSurface></div>
    </div>
  </OpsPage>;
}

function SectionTitle({ eyebrow,title,detail }:{eyebrow:string;title:string;detail:string}) { return <div><p className="ops-eyebrow">{eyebrow}</p><h2 className="mt-1 text-[17px] font-[720] tracking-[-.025em] text-[#443b35]">{title}</h2><p className="mt-1 text-[9px] leading-4 text-[#958b83]">{detail}</p></div>; }
function DecisionCard({label,value,detail,danger=false}:{label:string;value:string;detail:string;danger?:boolean}) { return <div className="rounded-[14px] border border-[#e7dfd8] bg-[#fffdfa] p-4"><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#9c928a]">{label}</p><strong className={`mt-2 block text-[22px] tracking-[-.04em] ${danger ? "text-[#b65355]" : "text-[#4b423c]"}`}>{value}</strong><p className="mt-1 text-[8px] leading-4 text-[#9b9189]">{detail}</p></div>; }
function MoneyMini({label,value,warn=false}:{label:string;value:string;warn?:boolean}) { return <div className="rounded-[12px] bg-[#faf7f4] p-3"><p className="text-[8px] font-bold uppercase tracking-[.07em] text-[#9c928a]">{label}</p><strong className={`mt-1.5 block text-[10px] ${warn ? "text-[#a2662f]" : "text-[#514840]"}`}>{value}</strong></div>; }
function Empty({text}:{text:string}) { return <div className="p-5 text-center text-[9px] text-[#978d85]">{text}</div>; }
function TrendChart({ currency, points }:{currency:CrmCurrency;points:TrendPoint[]}) { const max = Math.max(1,...points.map((p)=>Math.max(p.revenue,p.cost,Math.abs(p.profit)))); return <OpsSurface eyebrow={currency} title="Monthly movement" description="Revenue, cost and profit proportions within this currency."><div className="space-y-3">{points.slice(-12).map((p)=><div key={`${p.month}-${p.currency}`}><div className="mb-1 flex items-center justify-between gap-3"><span className="text-[8px] font-bold text-[#71675f]">{p.month}</span><span className={`text-[8px] font-semibold ${p.profit<0?"text-[#b65355]":"text-[#66806b]"}`}>{money(p.profit,currency)} profit</span></div><div className="grid grid-cols-[1fr_1fr] gap-1"><div className="h-1.5 overflow-hidden rounded-full bg-[#eee7e1]"><div className="h-full rounded-full bg-[#d8876f]" style={{width:`${Math.max(1,p.revenue/max*100)}%`}}/></div><div className="h-1.5 overflow-hidden rounded-full bg-[#eee7e1]"><div className="h-full rounded-full bg-[#9baaa0]" style={{width:`${Math.max(1,p.cost/max*100)}%`}}/></div></div></div>)}</div><div className="mt-3 flex gap-4 text-[8px] text-[#91877f]"><span>Coral · revenue</span><span>Sage · cost</span></div></OpsSurface>; }
