import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { locations } from "../company-data";
import { Container } from "../components/container";
import { NepalOperationsMap } from "../components/operations-map";
import { PageShell } from "../components/page-shell";
export default function NetworkPage(){return <PageShell eyebrow="Operational network" title="From Nepal's trade gateways to global markets." intro="KCPL connects its Kathmandu head office, Nepal and India operational locations, customs-entry-point personnel and international counterparts.">
  <section className="regional-network-section bg-offwhite py-20 lg:py-28"><Container><div className="mb-12 grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="eyebrow text-gold">Nepal &amp; India network</p><h2 className="section-title mt-4 text-navy">Built across Nepal&apos;s trade gateways.</h2></div><p className="max-w-xl text-base leading-8 text-slate lg:justify-self-end">Explore KCPL&apos;s confirmed operational locations across Nepal and India against the real Himalayan landscape.</p></div><NepalOperationsMap/></Container></section>
  <section id="confirmed-locations" className="section bg-white"><Container><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-gold">Confirmed locations</p><h2 className="section-title mt-4">A network shaped by Nepal&apos;s trade routes.</h2></div><div><p className="max-w-2xl text-base leading-8 text-slate">Kathmandu serves as the head-office origin. KCPL&apos;s other confirmed operational locations support Nepal coverage and the cross-border corridor toward India&apos;s transport and port connections.</p><div className="location-list mt-10">{locations.map((location,index)=><div key={location}><span>0{index+1}</span><strong>{location}</strong><small>{index===0?"Head office":index<4?"Nepal operational location":"India operational location"}</small></div>)}</div></div></div></Container></section>
  <section className="section bg-offwhite"><Container><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow text-gold">Customs-entry-point coverage</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.045em] text-navy">Present where Nepal trades.</h2><p className="mt-6 text-base leading-8 text-slate">KCPL combines its branch network with personnel positioned across Nepal&apos;s customs entry points to support documentation, coordination and cargo movement through key trade gateways.</p></div><div className="border-l border-line pl-7 lg:pl-12"><p className="eyebrow text-gold">International coordination</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.045em] text-navy">Counterparts, not claimed offices.</h2><p className="mt-6 text-base leading-8 text-slate">For cargo moving beyond the confirmed network, KCPL coordinates with international logistics counterparts. This extends shipment coordination without implying KCPL-owned offices in every market.</p><Link href="/quote" className="text-link mt-8">Plan a route <ArrowRight size={16}/></Link></div></div></Container></section>
</PageShell>}
